// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  general: [{ type: "autogenerated", dirName: "." }],
  openApiSidebar: [
    {
      type: "category",
      label: "Core",
      link: {
        type: "generated-index",
        title: "Core API",
        description: "Core API",
        slug: "/core",
      },
      items: require("./docs/v1.0/core/sidebar.ts"),
    },
  ],
};

export default sidebars;
