/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Swipe Games Integration Adapter Public API
 * This is the Integration Adapter API for Swipe Games Public API.
It is used to make reverse calls to integrations working through Public API.
Please implement this API on your side to support Swipe Games Public API.

 * OpenAPI spec version: 1.2.16
 */
/**
 * Error code. Could be handled by client accordingly (with localized message and related action).
 */
export type ErrorResponseWithCodeAndActionCode = typeof ErrorResponseWithCodeAndActionCode[keyof typeof ErrorResponseWithCodeAndActionCode];


export const ErrorResponseWithCodeAndActionCode = {
  game_not_found: 'game_not_found',
  currency_not_supported: 'currency_not_supported',
  locale_not_supported: 'locale_not_supported',
  account_blocked: 'account_blocked',
  bet_limit: 'bet_limit',
  loss_limit: 'loss_limit',
  time_limit: 'time_limit',
  insufficient_funds: 'insufficient_funds',
  session_expired: 'session_expired',
  session_not_found: 'session_not_found',
  client_connection_error: 'client_connection_error',
} as const;

/**
 * Required client action.
- `refresh` - shows a refresh button to the player. Player cannot continue without refreshing the game page.
     It's useful when the game session expires or the game is not available anymore. Once page is refreshed,
     the game will be reloaded and the player can continue playing. This might not work when games aren't embedded
     in the casino, but are opened in a new tab or window, since it will reopen the game again.

 */
export type ErrorResponseWithCodeAndActionAction = typeof ErrorResponseWithCodeAndActionAction[keyof typeof ErrorResponseWithCodeAndActionAction];


export const ErrorResponseWithCodeAndActionAction = {
  refresh: 'refresh',
} as const;

/**
 * Error code.
 */
export type ErrorResponseCode = typeof ErrorResponseCode[keyof typeof ErrorResponseCode];


export const ErrorResponseCode = {
  game_not_found: 'game_not_found',
  currency_not_supported: 'currency_not_supported',
  locale_not_supported: 'locale_not_supported',
  account_blocked: 'account_blocked',
  bet_limit: 'bet_limit',
  loss_limit: 'loss_limit',
  time_limit: 'time_limit',
  insufficient_funds: 'insufficient_funds',
  session_expired: 'session_expired',
  session_not_found: 'session_not_found',
  client_connection_error: 'client_connection_error',
} as const;

/**
 * General error response for Swipe Games Public API. Usually used for Public API responses.

 */
export interface ErrorResponse {
  /** A brief description of the error in English. Could be shown to the player. */
  message: string;
  /** Technical details for the error. Could be used for debugging, should not be shown to the player. */
  details?: string;
  /** Error code. */
  code?: ErrorResponseCode;
}

/**
 * Error response for Swipe Games Integration Adapter Public API. In additional to the common error response,
it contains an action field that describes the required client action (could be omit). If error code is provided in additional
client will handle it accordingly and with priority over action.
You can provide either message or message and code. Code always has
priority over message when both are provided. It means if you provide code, the client will handle it accordingly with some localized messaage,
related to the code. If you provide only message, the client will show it to the player as is.

 */
export type ErrorResponseWithCodeAndAction = ErrorResponse & {
  /** Error code. Could be handled by client accordingly (with localized message and related action). */
  code?: ErrorResponseWithCodeAndActionCode;
  /** Required client action.
- `refresh` - shows a refresh button to the player. Player cannot continue without refreshing the game page.
     It's useful when the game session expires or the game is not available anymore. Once page is refreshed,
     the game will be reloaded and the player can continue playing. This might not work when games aren't embedded
     in the casino, but are opened in a new tab or window, since it will reopen the game again.
 */
  action?: ErrorResponseWithCodeAndActionAction;
  /** Client action related data.
You can pass additional data to the client action. Not all actions require this field.
 */
  actionData?: string;
};

export interface BalanceResponse {
  /**
   * The player's balance in selected currency **main** units (**not cents**).
Currency selected by the client during the `Create New Game` call.
We support 2 decimal places for all fiat currencies.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  balance: string;
}

/**
 * The type of the bet.
- `regular` type means regular bet,
- `free` type means free bet (see Free Rounds section).

 */
export type BetRequestType = typeof BetRequestType[keyof typeof BetRequestType];


export const BetRequestType = {
  regular: 'regular',
  free: 'free',
} as const;

export interface BetRequest {
  /** The type of the bet.
- `regular` type means regular bet,
- `free` type means free bet (see Free Rounds section).
 */
  type: BetRequestType;
  /** The Game Session's ID (external). Provided by client via `Create New Game` call.
 */
  sessionID: string;
  /**
   * The amount of the bet in currency **main** units (**not cents**).
Currency selected by the client during the `Create New Game` call.
We support 2 decimal places for all fiat currencies.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  amount: string;
  /** Unique ID for the bet (internal) on Swipe Games' side.
Could be used as idempotency key.
 */
  txID: string;
  /** Non unique ID for the round (internal) on Swipe Games' side.
Could be the same for different games.
 */
  roundID: string;
  /** Free Rounds ID (external).
This field is provided only for free rounds bets (where `type` is `free`).
 */
  frID?: string;
}

export interface BetResponse {
  /**
   * The player's balance in selected currency **main** units (note: not cents) after the bet is applied.
Currency selected by the client during the `Create New Game` call.
We support 2 decimal places for all fiat currencies.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  balance: string;
  /** Unique ID for the bet on your side. This is required for further tracking/debugging purposes. */
  txID: string;
}

/**
 * The type of the win.
- `regular` type means regular bet,
- `free` type means free bet (see Free Rounds section).

 */
export type WinRequestType = typeof WinRequestType[keyof typeof WinRequestType];


export const WinRequestType = {
  regular: 'regular',
  free: 'free',
} as const;

export interface WinRequest {
  /** The type of the win.
- `regular` type means regular bet,
- `free` type means free bet (see Free Rounds section).
 */
  type: WinRequestType;
  /** The Game Session's ID (external). Provided by client via `Create New Game` call.
 */
  sessionID: string;
  /**
   * The amount of the bet in currency **main** units (note: not cents). Currency selected by the client during the
`Create New Game` call. We support 2 decimal places for all fiat currencies.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  amount: string;
  /** Unique ID for the win (internal) on Swipe Games' side.
Could be used as idempotency key.
 */
  txID: string;
  /** Non unique ID for the round (internal) on Swipe Games' side.
Could be the same for different games.
 */
  roundID: string;
  /** Free Rounds ID (external).
This field is provided only for free rounds wins (where `type` is `free`),
during bonus balance withdrawal process (type is `regular`).
 */
  frID?: string;
}

export interface WinResponse {
  /**
   * The player's balance in selected currency **main** units (note: not cents) after the win is applied.
Currency selected by the client during the `Create New Game` call.
We support 2 decimal places for all fiat currencies.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  balance: string;
  /** Unique ID for the win on your side. This is required for further tracking/debugging purposes. */
  txID: string;
}

export interface RefundRequest {
  /** The Game Session's ID (external). Provided by client via `Create New Game` call.
 */
  sessionID: string;
  /** Unique ID for the refund (internal) on Swipe Games' side.
Could be used as idempotency key.
 */
  txID: string;
  /** Original transaction ID (internal) on Swipe Games' side.
This is the ID of the transaction that should be refunded.
In some cases this original transaction ID might be not recorded on your side (timeout, server side error, etc).
 */
  origTxID: string;
  /**
   * The amount of the refund in currency **main** units (note: not cents).
Currency selected by the client during the `Create New Game` call.
We support 2 decimal places for all fiat currencies.
Refunds are always done for the whole bet amount.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  amount: string;
}

export interface RefundResponse {
  /**
   * The user's balance in selected currency **main** units (note: not cents) after the refund is applied.
Currency selected by the client during the `Create New Game` call.
We support 2 decimal places for all fiat currencies.

   * @pattern ^(0|[1-9]\d*)(\.\d+)?$
   */
  balance: string;
  /** Unique ID for the refund on your side. This is required for further tracking/debugging purposes. */
  txID: string;
}

export interface User {
  /** User's ID (external). This is User's ID on your side. */
  id: string;
  firstName?: string;
  lastName?: string;
  nickName?: string;
  /** Country code ISO 3166-1 alpha-2. */
  country?: string;
}

export type GetBalanceParams = {
/**
 * Session ID (external). Provided by client via `Create New Game` call.
This is your Session ID. We use it in all reverse calls to you.

 */
sessionID: string;
};

/**
 * This endpoint is used to get the player's balance.
Please make sure that this endpoint responds as quickly as possible,
so player's experience is not affected.

 * @summary Get balance
 */
export type getBalanceResponse200 = {
  data: BalanceResponse
  status: 200
}

export type getBalanceResponse401 = {
  data: ErrorResponseWithCodeAndAction
  status: 401
}

export type getBalanceResponse404 = {
  data: ErrorResponseWithCodeAndAction
  status: 404
}

export type getBalanceResponse500 = {
  data: ErrorResponseWithCodeAndAction
  status: 500
}

export type getBalanceResponseSuccess = (getBalanceResponse200) & {
  headers: Headers;
};
export type getBalanceResponseError = (getBalanceResponse401 | getBalanceResponse404 | getBalanceResponse500) & {
  headers: Headers;
};

export type getBalanceResponse = (getBalanceResponseSuccess | getBalanceResponseError)

export const getGetBalanceUrl = (params: GetBalanceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/balance?${stringifiedParams}` : `/balance`
}

export const getBalance = async (params: GetBalanceParams, options?: RequestInit): Promise<getBalanceResponse> => {
  
  const res = await fetch(getGetBalanceUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getBalanceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBalanceResponse
}
  


/**
 * This endpoint is used to place a bet in the game.
Every time player places a bet, we send a request to this endpoint and wait for the answer (**sync request**).

Please make sure that this endpoint responds as quickly as possible,
so player's experience is not affected.

In case we receive not 200 (OK) response or 5 seconds timeout we will send following `refund request.

 * @summary Bet
 */
export type postBetResponse200 = {
  data: BetResponse
  status: 200
}

export type postBetResponse400 = {
  data: ErrorResponseWithCodeAndAction
  status: 400
}

export type postBetResponse401 = {
  data: ErrorResponseWithCodeAndAction
  status: 401
}

export type postBetResponse404 = {
  data: ErrorResponseWithCodeAndAction
  status: 404
}

export type postBetResponse500 = {
  data: ErrorResponseWithCodeAndAction
  status: 500
}

export type postBetResponseSuccess = (postBetResponse200) & {
  headers: Headers;
};
export type postBetResponseError = (postBetResponse400 | postBetResponse401 | postBetResponse404 | postBetResponse500) & {
  headers: Headers;
};

export type postBetResponse = (postBetResponseSuccess | postBetResponseError)

export const getPostBetUrl = () => {


  

  return `/bet`
}

export const postBet = async (betRequest: BetRequest, options?: RequestInit): Promise<postBetResponse> => {
  
  const res = await fetch(getPostBetUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      betRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postBetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postBetResponse
}
  


/**
 * This endpoint is used to place a win in the game.

Every time player wins, or round ended without a win (in this case amount is 0),
we send a request to this endpoint and wait for the answer. Wait time is 5 seconds.

After timeout or any error this request will be retrying in the background until we receive 200(OK) response.

 * @summary Win
 */
export type postWinResponse200 = {
  data: WinResponse
  status: 200
}

export type postWinResponse400 = {
  data: ErrorResponseWithCodeAndAction
  status: 400
}

export type postWinResponse401 = {
  data: ErrorResponseWithCodeAndAction
  status: 401
}

export type postWinResponse404 = {
  data: ErrorResponseWithCodeAndAction
  status: 404
}

export type postWinResponse500 = {
  data: ErrorResponseWithCodeAndAction
  status: 500
}

export type postWinResponseSuccess = (postWinResponse200) & {
  headers: Headers;
};
export type postWinResponseError = (postWinResponse400 | postWinResponse401 | postWinResponse404 | postWinResponse500) & {
  headers: Headers;
};

export type postWinResponse = (postWinResponseSuccess | postWinResponseError)

export const getPostWinUrl = () => {


  

  return `/win`
}

export const postWin = async (winRequest: WinRequest, options?: RequestInit): Promise<postWinResponse> => {
  
  const res = await fetch(getPostWinUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      winRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postWinResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postWinResponse
}
  


/**
 * This endpoint is used to place a refund for bet or win action.
We send refund to the client side in case of Bet 500 error or timeout, also
in case when player cancels the game.

After timeout or any error this request will be retrying until we receive 200(OK) response.

 * @summary Refund
 */
export type postRefundResponse200 = {
  data: RefundResponse
  status: 200
}

export type postRefundResponse400 = {
  data: ErrorResponseWithCodeAndAction
  status: 400
}

export type postRefundResponse401 = {
  data: ErrorResponseWithCodeAndAction
  status: 401
}

export type postRefundResponse404 = {
  data: ErrorResponseWithCodeAndAction
  status: 404
}

export type postRefundResponse500 = {
  data: ErrorResponseWithCodeAndAction
  status: 500
}

export type postRefundResponseSuccess = (postRefundResponse200) & {
  headers: Headers;
};
export type postRefundResponseError = (postRefundResponse400 | postRefundResponse401 | postRefundResponse404 | postRefundResponse500) & {
  headers: Headers;
};

export type postRefundResponse = (postRefundResponseSuccess | postRefundResponseError)

export const getPostRefundUrl = () => {


  

  return `/refund`
}

export const postRefund = async (refundRequest: RefundRequest, options?: RequestInit): Promise<postRefundResponse> => {
  
  const res = await fetch(getPostRefundUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refundRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postRefundResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postRefundResponse
}
