// Package swipegamesintegrationapiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package swipegamesintegrationapiv1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	uuid "github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BetRequestType.
const (
	BetRequestTypeFree    BetRequestType = "free"
	BetRequestTypeRegular BetRequestType = "regular"
)

// Valid indicates whether the value is a known member of the BetRequestType enum.
func (e BetRequestType) Valid() bool {
	switch e {
	case BetRequestTypeFree:
		return true
	case BetRequestTypeRegular:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseWithCodeAndActionAction.
const (
	Refresh ErrorResponseWithCodeAndActionAction = "refresh"
)

// Valid indicates whether the value is a known member of the ErrorResponseWithCodeAndActionAction enum.
func (e ErrorResponseWithCodeAndActionAction) Valid() bool {
	switch e {
	case Refresh:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseWithCodeAndActionCode.
const (
	AccountBlocked        ErrorResponseWithCodeAndActionCode = "account_blocked"
	BetLimit              ErrorResponseWithCodeAndActionCode = "bet_limit"
	ClientConnectionError ErrorResponseWithCodeAndActionCode = "client_connection_error"
	CurrencyNotSupported  ErrorResponseWithCodeAndActionCode = "currency_not_supported"
	GameNotFound          ErrorResponseWithCodeAndActionCode = "game_not_found"
	InsufficientFunds     ErrorResponseWithCodeAndActionCode = "insufficient_funds"
	LocaleNotSupported    ErrorResponseWithCodeAndActionCode = "locale_not_supported"
	LossLimit             ErrorResponseWithCodeAndActionCode = "loss_limit"
	SessionExpired        ErrorResponseWithCodeAndActionCode = "session_expired"
	SessionNotFound       ErrorResponseWithCodeAndActionCode = "session_not_found"
	TimeLimit             ErrorResponseWithCodeAndActionCode = "time_limit"
)

// Valid indicates whether the value is a known member of the ErrorResponseWithCodeAndActionCode enum.
func (e ErrorResponseWithCodeAndActionCode) Valid() bool {
	switch e {
	case AccountBlocked:
		return true
	case BetLimit:
		return true
	case ClientConnectionError:
		return true
	case CurrencyNotSupported:
		return true
	case GameNotFound:
		return true
	case InsufficientFunds:
		return true
	case LocaleNotSupported:
		return true
	case LossLimit:
		return true
	case SessionExpired:
		return true
	case SessionNotFound:
		return true
	case TimeLimit:
		return true
	default:
		return false
	}
}

// Defines values for WinRequestType.
const (
	WinRequestTypeFree    WinRequestType = "free"
	WinRequestTypeRegular WinRequestType = "regular"
)

// Valid indicates whether the value is a known member of the WinRequestType enum.
func (e WinRequestType) Valid() bool {
	switch e {
	case WinRequestTypeFree:
		return true
	case WinRequestTypeRegular:
		return true
	default:
		return false
	}
}

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	// Balance The player's balance in selected currency **main** units (**not cents**).
	// Currency selected by the client during the `Create New Game` call.
	// Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	Balance string `json:"balance"`
}

// BetRequest defines model for BetRequest.
type BetRequest struct {
	// Amount The amount of the bet in currency **main** units (**not cents**).
	// Currency selected by the client during the `Create New Game` call.
	// Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	Amount string `json:"amount"`

	// FrID Free Rounds ID (external).
	// This field is provided only for free rounds bets (where `type` is `free`).
	FrID *string `json:"frID,omitempty"`

	// RoundID Non unique ID for the round (internal) on Swipe Games' side.
	// Could be the same for different games.
	RoundID uuid.UUID `json:"roundID"`

	// SessionID Session ID (external). This is your own Session ID, the exact value you provided in the `sessionID` field of the `Create New Game` call.
	// It is NOT the `gsID` (Game Session ID) returned by `Create New Game`, which is Swipe Games's own identifier and is never sent in reverse calls.
	SessionID string `json:"sessionID"`

	// TxID Globally unique identifier (UUID v4) for the bet transaction on Swipe Games' side.
	// Must be used as an idempotency key on your side.
	// Uniqueness is guaranteed by Swipe Games for a rolling 3-month window.
	// For uniqueness guarantees beyond 3 months, use the composite key (`txID` + `roundID`).
	TxID uuid.UUID `json:"txID"`

	// Type The type of the bet.
	// - `regular` type means regular bet,
	// - `free` type means free bet (see Free Rounds section).
	Type BetRequestType `json:"type"`
}

// BetRequestType The type of the bet.
// - `regular` type means regular bet,
// - `free` type means free bet (see Free Rounds section).
type BetRequestType string

// BetResponse defines model for BetResponse.
type BetResponse struct {
	// Balance The player's balance in selected currency **main** units (note: not cents) after the bet is applied.
	// Currency selected by the client during the `Create New Game` call.
	// Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	Balance string `json:"balance"`

	// TxID Unique ID for the bet on your side. This is required for further tracking/debugging purposes.
	TxID string `json:"txID"`
}

// ErrorResponseWithCodeAndAction Error response for Swipe Games Integration Adapter Public API. In additional to the common error response,
// it contains an action field that describes the required client action (could be omit). If error code is provided in additional
// client will handle it accordingly and with priority over action.
// You can provide either message or message and code. Code always has
// priority over message when both are provided. It means if you provide code, the client will handle it accordingly with some localized messaage,
// related to the code. If you provide only message, the client will show it to the player as is.
type ErrorResponseWithCodeAndAction struct {
	// Action Required client action.
	// - `refresh` - shows a refresh button to the player. Player cannot continue without refreshing the game page.
	//      It's useful when the game session expires or the game is not available anymore. Once page is refreshed,
	//      the game will be reloaded and the player can continue playing. This might not work when games aren't embedded
	//      in the casino, but are opened in a new tab or window, since it will reopen the game again.
	Action *ErrorResponseWithCodeAndActionAction `json:"action,omitempty"`

	// ActionData Client action related data.
	// You can pass additional data to the client action. Not all actions require this field.
	ActionData *string `json:"actionData,omitempty"`

	// Code Error code. Could be handled by client accordingly (with localized message and related action).
	Code *ErrorResponseWithCodeAndActionCode `json:"code,omitempty"`

	// Details Technical details for the error. Could be used for debugging, should not be shown to the player.
	Details *string `json:"details,omitempty"`

	// Message A brief description of the error in English. Could be shown to the player.
	Message string `json:"message"`
}

// ErrorResponseWithCodeAndActionAction Required client action.
//   - `refresh` - shows a refresh button to the player. Player cannot continue without refreshing the game page.
//     It's useful when the game session expires or the game is not available anymore. Once page is refreshed,
//     the game will be reloaded and the player can continue playing. This might not work when games aren't embedded
//     in the casino, but are opened in a new tab or window, since it will reopen the game again.
type ErrorResponseWithCodeAndActionAction string

// ErrorResponseWithCodeAndActionCode Error code. Could be handled by client accordingly (with localized message and related action).
type ErrorResponseWithCodeAndActionCode string

// RefundRequest defines model for RefundRequest.
type RefundRequest struct {
	// Amount The amount of the refund in currency **main** units (note: not cents).
	// Currency selected by the client during the `Create New Game` call.
	// Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	// Refunds are always done for the whole bet amount.
	Amount string `json:"amount"`

	// OrigTxID Original transaction ID (internal) on Swipe Games' side.
	// This is the ID of the transaction that should be refunded.
	// In some cases this original transaction ID might be not recorded on your side (timeout, server side error, etc).
	OrigTxID uuid.UUID `json:"origTxID"`

	// RoundID Non unique ID for the round (internal) on Swipe Games' side.
	// Could be the same for different games.
	// Added in version 1.5.0. This field is optional for backward compatibility.
	RoundID *uuid.UUID `json:"roundID,omitempty"`

	// SessionID Session ID (external). This is your own Session ID, the exact value you provided in the `sessionID` field of the `Create New Game` call.
	// It is NOT the `gsID` (Game Session ID) returned by `Create New Game`, which is Swipe Games's own identifier and is never sent in reverse calls.
	SessionID string `json:"sessionID"`

	// TxID Globally unique identifier (UUID v4) for the refund transaction on Swipe Games' side.
	// Must be used as an idempotency key on your side.
	// Uniqueness is guaranteed by Swipe Games for a rolling 3-month window.
	// For uniqueness guarantees beyond 3 months, use the composite key (`txID` + `roundID`).
	TxID uuid.UUID `json:"txID"`
}

// RefundResponse defines model for RefundResponse.
type RefundResponse struct {
	// Balance The user's balance in selected currency **main** units (note: not cents) after the refund is applied.
	// Currency selected by the client during the `Create New Game` call.
	// Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	Balance string `json:"balance"`

	// TxID Unique ID for the refund on your side. This is required for further tracking/debugging purposes.
	TxID string `json:"txID"`
}

// WinRequest defines model for WinRequest.
type WinRequest struct {
	// Amount The amount of the bet in currency **main** units (note: not cents). Currency selected by the client during the
	// `Create New Game` call. Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	Amount string `json:"amount"`

	// FrID Free Rounds ID (external).
	// This field is provided only for free rounds wins (where `type` is `free`),
	// during bonus balance withdrawal process (type is `regular`).
	FrID *string `json:"frID,omitempty"`

	// RoundID Non unique ID for the round (internal) on Swipe Games' side.
	// Could be the same for different games.
	RoundID uuid.UUID `json:"roundID"`

	// SessionID Session ID (external). This is your own Session ID, the exact value you provided in the `sessionID` field of the `Create New Game` call.
	// It is NOT the `gsID` (Game Session ID) returned by `Create New Game`, which is Swipe Games's own identifier and is never sent in reverse calls.
	SessionID string `json:"sessionID"`

	// TxID Globally unique identifier (UUID v4) for the win transaction on Swipe Games' side.
	// Must be used as an idempotency key on your side.
	// Uniqueness is guaranteed by Swipe Games for a rolling 3-month window.
	// For uniqueness guarantees beyond 3 months, use the composite key (`txID` + `roundID`).
	TxID uuid.UUID `json:"txID"`

	// Type The type of the win.
	// - `regular` type means regular bet,
	// - `free` type means free bet (see Free Rounds section).
	Type WinRequestType `json:"type"`
}

// WinRequestType The type of the win.
// - `regular` type means regular bet,
// - `free` type means free bet (see Free Rounds section).
type WinRequestType string

// WinResponse defines model for WinResponse.
type WinResponse struct {
	// Balance The player's balance in selected currency **main** units (note: not cents) after the win is applied.
	// Currency selected by the client during the `Create New Game` call.
	// Fiat currencies carry **up to** 2 decimal places; some (e.g. `JPY`, `KRW`, `VND`) carry none.
	Balance string `json:"balance"`

	// TxID Unique ID for the win on your side. This is required for further tracking/debugging purposes.
	TxID string `json:"txID"`
}

// GetBalanceParams defines parameters for GetBalance.
type GetBalanceParams struct {
	// SessionID Session ID (external). This is your own Session ID, the exact value you provided in the `sessionID` field of the `Create New Game` call.
	// We store it and pass it back in all reverse calls to you.
	//
	// Note: this is NOT the `gsID` (Game Session ID) returned by `Create New Game`. `gsID` is Swipe Games's own identifier and is never sent in reverse calls.
	SessionID string `form:"sessionID" json:"sessionID"`

	// XREQUESTSIGN Request signature (see [Verifying Request Signatures](/swipegames-integration#verifying-request-signatures) for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// PostBetParams defines parameters for PostBet.
type PostBetParams struct {
	// XREQUESTSIGN Request signature (see [Verifying Request Signatures](/swipegames-integration#verifying-request-signatures) for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// PostRefundParams defines parameters for PostRefund.
type PostRefundParams struct {
	// XREQUESTSIGN Request signature (see [Verifying Request Signatures](/swipegames-integration#verifying-request-signatures) for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// PostWinParams defines parameters for PostWin.
type PostWinParams struct {
	// XREQUESTSIGN Request signature (see [Verifying Request Signatures](/swipegames-integration#verifying-request-signatures) for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// PostBetJSONRequestBody defines body for PostBet for application/json ContentType.
type PostBetJSONRequestBody = BetRequest

// PostRefundJSONRequestBody defines body for PostRefund for application/json ContentType.
type PostRefundJSONRequestBody = RefundRequest

// PostWinJSONRequestBody defines body for PostWin for application/json ContentType.
type PostWinJSONRequestBody = WinRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetBalance request
	GetBalance(ctx context.Context, params *GetBalanceParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostBetWithBody request with any body
	PostBetWithBody(ctx context.Context, params *PostBetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostBet(ctx context.Context, params *PostBetParams, body PostBetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRefundWithBody request with any body
	PostRefundWithBody(ctx context.Context, params *PostRefundParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRefund(ctx context.Context, params *PostRefundParams, body PostRefundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostWinWithBody request with any body
	PostWinWithBody(ctx context.Context, params *PostWinParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostWin(ctx context.Context, params *PostWinParams, body PostWinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetBalance(ctx context.Context, params *GetBalanceParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBalanceRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBetWithBody(ctx context.Context, params *PostBetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBetRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostBet(ctx context.Context, params *PostBetParams, body PostBetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostBetRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRefundWithBody(ctx context.Context, params *PostRefundParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRefundRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRefund(ctx context.Context, params *PostRefundParams, body PostRefundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRefundRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWinWithBody(ctx context.Context, params *PostWinParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWinRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostWin(ctx context.Context, params *PostWinParams, body PostWinJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostWinRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetBalanceRequest generates requests for GetBalance
func NewGetBalanceRequest(server string, params *GetBalanceParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/balance")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sessionID", params.SessionID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-REQUEST-SIGN", params.XREQUESTSIGN, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

// NewPostBetRequest calls the generic PostBet builder with application/json body
func NewPostBetRequest(server string, params *PostBetParams, body PostBetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostBetRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostBetRequestWithBody generates requests for PostBet with any type of body
func NewPostBetRequestWithBody(server string, params *PostBetParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/bet")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-REQUEST-SIGN", params.XREQUESTSIGN, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

// NewPostRefundRequest calls the generic PostRefund builder with application/json body
func NewPostRefundRequest(server string, params *PostRefundParams, body PostRefundJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRefundRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostRefundRequestWithBody generates requests for PostRefund with any type of body
func NewPostRefundRequestWithBody(server string, params *PostRefundParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/refund")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-REQUEST-SIGN", params.XREQUESTSIGN, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

// NewPostWinRequest calls the generic PostWin builder with application/json body
func NewPostWinRequest(server string, params *PostWinParams, body PostWinJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostWinRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostWinRequestWithBody generates requests for PostWin with any type of body
func NewPostWinRequestWithBody(server string, params *PostWinParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/win")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-REQUEST-SIGN", params.XREQUESTSIGN, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetBalanceWithResponse request
	GetBalanceWithResponse(ctx context.Context, params *GetBalanceParams, reqEditors ...RequestEditorFn) (*GetBalanceResponse, error)

	// PostBetWithBodyWithResponse request with any body
	PostBetWithBodyWithResponse(ctx context.Context, params *PostBetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBetResponse, error)

	PostBetWithResponse(ctx context.Context, params *PostBetParams, body PostBetJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBetResponse, error)

	// PostRefundWithBodyWithResponse request with any body
	PostRefundWithBodyWithResponse(ctx context.Context, params *PostRefundParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRefundResponse, error)

	PostRefundWithResponse(ctx context.Context, params *PostRefundParams, body PostRefundJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRefundResponse, error)

	// PostWinWithBodyWithResponse request with any body
	PostWinWithBodyWithResponse(ctx context.Context, params *PostWinParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWinResponse, error)

	PostWinWithResponse(ctx context.Context, params *PostWinParams, body PostWinJSONRequestBody, reqEditors ...RequestEditorFn) (*PostWinResponse, error)
}

type GetBalanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BalanceResponse
	JSON401      *ErrorResponseWithCodeAndAction
	JSON404      *ErrorResponseWithCodeAndAction
	JSON500      *ErrorResponseWithCodeAndAction
}

// Status returns HTTPResponse.Status
func (r GetBalanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBalanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBalanceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostBetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BetResponse
	JSON400      *ErrorResponseWithCodeAndAction
	JSON401      *ErrorResponseWithCodeAndAction
	JSON404      *ErrorResponseWithCodeAndAction
	JSON500      *ErrorResponseWithCodeAndAction
}

// Status returns HTTPResponse.Status
func (r PostBetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostBetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostBetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostRefundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RefundResponse
	JSON400      *ErrorResponseWithCodeAndAction
	JSON401      *ErrorResponseWithCodeAndAction
	JSON404      *ErrorResponseWithCodeAndAction
	JSON500      *ErrorResponseWithCodeAndAction
}

// Status returns HTTPResponse.Status
func (r PostRefundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRefundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostRefundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostWinResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WinResponse
	JSON400      *ErrorResponseWithCodeAndAction
	JSON401      *ErrorResponseWithCodeAndAction
	JSON404      *ErrorResponseWithCodeAndAction
	JSON500      *ErrorResponseWithCodeAndAction
}

// Status returns HTTPResponse.Status
func (r PostWinResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostWinResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostWinResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetBalanceWithResponse request returning *GetBalanceResponse
func (c *ClientWithResponses) GetBalanceWithResponse(ctx context.Context, params *GetBalanceParams, reqEditors ...RequestEditorFn) (*GetBalanceResponse, error) {
	rsp, err := c.GetBalance(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBalanceResponse(rsp)
}

// PostBetWithBodyWithResponse request with arbitrary body returning *PostBetResponse
func (c *ClientWithResponses) PostBetWithBodyWithResponse(ctx context.Context, params *PostBetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostBetResponse, error) {
	rsp, err := c.PostBetWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBetResponse(rsp)
}

func (c *ClientWithResponses) PostBetWithResponse(ctx context.Context, params *PostBetParams, body PostBetJSONRequestBody, reqEditors ...RequestEditorFn) (*PostBetResponse, error) {
	rsp, err := c.PostBet(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostBetResponse(rsp)
}

// PostRefundWithBodyWithResponse request with arbitrary body returning *PostRefundResponse
func (c *ClientWithResponses) PostRefundWithBodyWithResponse(ctx context.Context, params *PostRefundParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRefundResponse, error) {
	rsp, err := c.PostRefundWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRefundResponse(rsp)
}

func (c *ClientWithResponses) PostRefundWithResponse(ctx context.Context, params *PostRefundParams, body PostRefundJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRefundResponse, error) {
	rsp, err := c.PostRefund(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRefundResponse(rsp)
}

// PostWinWithBodyWithResponse request with arbitrary body returning *PostWinResponse
func (c *ClientWithResponses) PostWinWithBodyWithResponse(ctx context.Context, params *PostWinParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostWinResponse, error) {
	rsp, err := c.PostWinWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWinResponse(rsp)
}

func (c *ClientWithResponses) PostWinWithResponse(ctx context.Context, params *PostWinParams, body PostWinJSONRequestBody, reqEditors ...RequestEditorFn) (*PostWinResponse, error) {
	rsp, err := c.PostWin(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostWinResponse(rsp)
}

// ParseGetBalanceResponse parses an HTTP response from a GetBalanceWithResponse call
func ParseGetBalanceResponse(rsp *http.Response) (*GetBalanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBalanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BalanceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostBetResponse parses an HTTP response from a PostBetWithResponse call
func ParsePostBetResponse(rsp *http.Response) (*PostBetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostBetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BetResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostRefundResponse parses an HTTP response from a PostRefundWithResponse call
func ParsePostRefundResponse(rsp *http.Response) (*PostRefundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRefundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RefundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostWinResponse parses an HTTP response from a PostWinWithResponse call
func ParsePostWinResponse(rsp *http.Response) (*PostWinResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostWinResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WinResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponseWithCodeAndAction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get balance
	// (GET /balance)
	GetBalance(ctx echo.Context, params GetBalanceParams) error
	// Bet
	// (POST /bet)
	PostBet(ctx echo.Context, params PostBetParams) error
	// Refund
	// (POST /refund)
	PostRefund(ctx echo.Context, params PostRefundParams) error
	// Win
	// (POST /win)
	PostWin(ctx echo.Context, params PostWinParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetBalance(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBalanceParams
	// ------------- Required query parameter "sessionID" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "sessionID", ctx.QueryParams(), &params.SessionID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionID: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBalance(ctx, params)
	return err
}

// PostBet converts echo context to params.
func (w *ServerInterfaceWrapper) PostBet(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostBetParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBet(ctx, params)
	return err
}

// PostRefund converts echo context to params.
func (w *ServerInterfaceWrapper) PostRefund(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostRefundParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRefund(ctx, params)
	return err
}

// PostWin converts echo context to params.
func (w *ServerInterfaceWrapper) PostWin(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostWinParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostWin(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/balance", wrapper.GetBalance, options.OperationMiddlewares["GetBalance"]...)
	router.POST(options.BaseURL+"/bet", wrapper.PostBet, options.OperationMiddlewares["PostBet"]...)
	router.POST(options.BaseURL+"/refund", wrapper.PostRefund, options.OperationMiddlewares["PostRefund"]...)
	router.POST(options.BaseURL+"/win", wrapper.PostWin, options.OperationMiddlewares["PostWin"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftrc9s2s/4rO2xnIruSLN+axOfDGSdOO2rnODlOUp9OlGOB5FJCTQIMAFrW2zf//Z1dgBRlyanbuEmb",
	"ql9ikbgs9vI8y1301yjRRakVKmejo18jm0yxEPznE5ELleAZ2lIri/SoNLpE4yTygNgPoD9TtImRpZNa",
	"RUfRqylCmYs5mgcWwiiQCizmmDhMIamMQZXMYXu7EFJtb0OlpLPQ2d5W2kFC0mxvb/VH6mk9spkbz8FN",
	"EZJconKQVkaqCT8ZPzUoHMIpzuB7UeAYEpHn/ZH6TgpXbynRQiKMoa2rEpze3oY9SDGRhchJ6ATtf4HV",
	"BUIH+5M+jH948fO4C+Mfz87pn59OT8ZbYQWlFfZHKupGeC2KMsfoKNodDPq7g6gblcI5NKSN/+8M/v1m",
	"t/f47WiUbm91RqP+aJR+s/XfX0fdyM1LmmUdnSJ6/74bGXxXSYNpdPSmUfDbZqCOf8HERe+70RN0Z/iu",
	"QutWDSMKXSm33i7+HeiMdRajI8Ns7LHeHt0oM8OTVUV+ZxDhTFcqtTA8gQ5e09oiJw29mkoLmcQ8BWmh",
	"NPpKppiCVvkcMm0go7nGz42RlDybokEY095jmjOmIeOtm0chJVzUO13QmAu/zIVM14nOL9dJf6oV2fdd",
	"hSQ8yUTm4uHQkSocBbSClzNZIhvPPgArU1LvU13lKcTIk6wokFdIZZahIQ+Y0OibsscPH+HBXvaotzc4",
	"2O0dPNpLe4+Tg7iX7SXi4eMseXiI+1E3yrQphIuOoqpac6ZudN2b6F54SEP6r18PT9rPe7IotWHXV6LA",
	"xUqlcNPoKJpIN63ifqKLnYnWkxx3+D0FnkVrpVbrFPbSv7phamBLSwtzXRnQMwWLcV3WDl6LxMGVyCuk",
	"QQtnkMpHSLPnOHhMCMtbQ2foaMPT56/8sImlqR0a0tp8Cwy6yigfnCtrdWE2lcmUFmrb1/IRZIrKyUyi",
	"AaHYgxVeoQFLppUKDP2yyPKsWFnsxnvJfnrQw8Ps297DR48HPREnaQ+z3b39g8Nv6ck6T3XX67T+fa5j",
	"kefz2ldbonXI7nB1sNV4LwGZM0JZkdD025z3fyrryHcriykIC4JPXJTaMahd4pxmskHDjNe8uULLpp5U",
	"wgjl0Ku2tQMLIsDoPCf82+8VWrkpzKRK9YwwT5twDl6qWYcwYK5VCvvAM2yXZPOISsRspUMWqzMmLY3h",
	"GxiHwF5FiGTvYZKIFHuH4uCwd7B7+LAnHh1mvYfpYG9ffPvoMYrDzxxlftl1xERvWrTUH6kejA1OqlyY",
	"sX9boFAWwjMa1OVBDJftEQyx5BEdiwhtsLbI7lFrTlUF8WxYkVRjkOl2odPFuw9zNb9to0i3puHg3wtA",
	"vpXOP2GipbTDI2jIfQtE5nARStKCKMtcYvoP5Pz1cPR6hTFJUUto0TBC7Rie8CvjpqRbI5JLqSY7KcbV",
	"ZEIqKytTaou2vyQ/LXjhrtXF7t7+nXPEIPY633pmjDa1d51LN32qUzxW6XHij3bzpDweTJjAZ2gj3VA5",
	"nBjBMHucipL85kUV5zKB4xfDPgwViDSV9F7k4HQNZoVWgEtLd0dKOki0ckIqBuOA3p4M3VQ48KLFaH2S",
	"Uis2uF4Y30nqpEQX0m31YZiFrRKd4lIeJtvSjVRYZybzHKZCpTmCpGUTbVKpJvmcaXAm3RRKI7WRbg6a",
	"CNHv3B+pn3UFiVD1DoCSrV2gtWKCoBd/0kokTx/IACDymZhbmAo7Ustr1xNmU1QQazcFYbA5Qh+GLgCd",
	"zNp5BS/ebUfmB47FR+IYy3UicvkvTP2+YkJ2MZgLivTGfCT2cHk7TmmDrKvb2qme0aZhBQ9TxLky5A03",
	"vlluccaztRav2SEzaKdj6PFulgjYP4K4ck6r5c378MILkQjFyKeVk6pC1oWuXD25BjPKZKEUEwIYoP+G",
	"7oEles6q3NumGRVgH/C6lAYtBITgd5RDaQfiSshcxDn5wbzQBvvwnOCaNvCYwZtj2g27NQuwOmNy/lwL",
	"8mFypJZOyfuas9AzqSYBiwo5mTrefqbNpReaE3TyKPXAARYxpimmYc+QmCbCSqW7pEV2PV2iCrEDCmfg",
	"RExH9NlNF6xk3gmGN0jDF+KLiZDqJuHyWVtotUBfb+AT4cSqMzxdivraR1PhRDsQhbVtBKLXjR8vORGc",
	"kl3yPPxucBtc8w3n5V4RkuLhNuCsQzwgkg8/5sxm90UYdjgOb4RgwIr6fCLkLC0FkmIvlHYXGeUUUTeq",
	"iZ4f2qqk/AzpBS+NK49Jhkq5izjXySU/idFd5LKQjidZ2/xwssDmh1S2yjKZ0EEuMsqpFknPhff+tPVk",
	"SUQ+/UWilfJZ2AVD9FonSNEJmds1GQ8mUyUTMqsf0rAxL9bSO6f4/Gla022XUILeUjzEyJhxEyLWGTvY",
	"ZFWYY4iNxAxaT+sM1rOPVPBMTXJppy3B7rbtDZqvZVjH72dIhriHapDhhT5YELqZN/490kOvIQa9mnZT",
	"rbDxndlU5z6f8wq574xSGzl5tTarfG7kRHKe1Pp4HZ7coQ5T55ok//CkNmF7Gc6fgsvHtXU5ox8qr79E",
	"WE6sJDHWekE8g8TINjdIyMXVrEXaCx1CCF25Llg0XCzgPIgioAvokr/jd+pnLp4dpyFXvULDicVu/7A/",
	"CKTeFBd1GSiOFolFcjkTJuW6gXAylrl0800hblOI+6SFuMAhm1rcXx3jbiQY7cJVqFc1rNWUsj6Uffyh",
	"4lVl77V0VScwm+rVb1evgq7+jALWcqeKPizc9dom1e+vZZ1L9QnanitZLtzdi0bqFjeCTd+z7nvOpLq9",
	"79kdqaDNWKtqAQ70pZwaMSP9GJ0QdHe46E9T60bBpmu6SdY2ydpdk7UZqXSTqX0hXdOZVP+wrilnA3+N",
	"rimF0ibvvEPeSYr6WyWdNEGqTK9zpFYJbk1X9PjFcKV72uqU1sTEsOo0FOISl6mCnsrFwpa7ON5rjK4m",
	"0+XVXuQoLIIkhRTkYlzYIyGWynVOQ+gE3C4Yl/0d6/Xurd+oG4VyFblT/1F/j2ufJSpRyugo2u8P+vsB",
	"7zhCd1ohOkF3i4JRpaWWaklVE3St8vkijBdaYGXaips5IqiiWck3oFNLZPauksllPqc/S22tjHPsjpTV",
	"i7XxukQjkVEi9PKyjEPaa4pAh3UyTImA0T1pXKoURhTo0Njo6M261iZaB1ZOlHAkKiPvm5/QyGxOZq5H",
	"vKxH2LedHUsG4Xyx1/KNr67qWT3jZ/Wada1n/EIbrNsmW9zLiY6iKYoUCagDJ/1f7+zZ/75+9vJV7+Xw",
	"+9OoHSvOVNgNN4TJVitx9dfNAM8RrKPjS8cZGvcIpeOiKbc1uW95I/LmuuqP1EidMuq7IPXHpZH9et5n",
	"yyPZ6u8qNPOF0dv8e3d7v6XBnn05nPcGA/on0cqh/w5nNkzYP3d+sb69v1jva4NZdBR9tbO4gr4T7p/v",
	"3Lx8zii87F36kuDlYLB7b5v+xkWZNTKcG60miwD2Ah18RoFeWzT+bgf769LlhOEJg5fvx77vRof3aK/f",
	"L+lL3yvyjVKdcJYTvimrohBm7rEUWvwsJgSj0VmIgqcUBdFbmrITe/ootf09NMJZE4i6HlRfWeiP1LMr",
	"NHNwsmhuWfgMyw/uwozUqlK+ceIxmhu67X344pCQrsl8hLIz+gzb3rZzldQT/b36T85b3ARMaMcZJR0J",
	"yivf49sbDKDz/MetxQUwbeCQvgF459Dro1n+mg9pIdN5rmfEWONQVgyHW0eQL7R1T9D909jxrR+M1j3R",
	"6fz+gHLx/4GsCbJaRbFO5+QENZG8+eHl81N4KpT2lym+06Z429kRlZuqr0iAXlK/69GH79bKUd//meDf",
	"ugy75lDPf/Q4+znR64lofHzDQl8IC90gH49RHyIdj3UfwTsBLLl9jy5cqVtccTwPJFP3VJfusPG3nAwY",
	"rjN4gg4OB4OaUA00tzJEbvVI1UP5DuDi5mCCuW0T30gd+5pGwHlNqeg8rMrWrAlvcS3RGcbjSjmZt+lk",
	"bzBYYpLb2MC3EDeEcC8xsHwb7IvhhBtt5g0tbGjh89BCA1YfYoaZVB9BC1xLVsuovPpBMpPKdgmffQ8S",
	"VYppc5XdL9LhVaT1yB964NLCYKs7Un/8E6YP5/SQhZF28XHwcfQRThyL5HLij/SHCeVcqg2b3EvotO5b",
	"fDFU0u4abXhkwyOfh0c8Rt1KIu/f/ycAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
