// Package coreapiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package coreapiv1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/swipegames/public-api/api/v1.0"
)

// Defines values for PlatformType.
const (
	Desktop PlatformType = "desktop"
	Mobile  PlatformType = "mobile"
)

// BetLineInfo defines model for BetLineInfo.
type BetLineInfo struct {
	// Currency Currency code in ISO4217
	Currency string `json:"currency"`

	// Values List of bet line values (0-indexed array maps to 1-based bet lines).
	Values []BetLineValue `json:"values"`
}

// BetLineValue defines model for BetLineValue.
type BetLineValue struct {
	// MaxBet Maximum bet amount for this line (in currency units)
	MaxBet string `json:"maxBet"`

	// MaxCoeff Maximum multiplier applied to the bet
	MaxCoeff string `json:"maxCoeff"`
}

// CreateFreeRoundsRequest defines model for CreateFreeRoundsRequest.
type CreateFreeRoundsRequest struct {
	// BetLine Number of bet line configured for this game/provider.
	BetLine int32 `json:"betLine"`

	// CID Client's ID (internal)
	CID openapi_types.UUID `json:"cID"`

	// Currency Currency code in ISO4217
	Currency string `json:"currency"`

	// ExtCID External Client's ID (game aggregator or casino)
	ExtCID string `json:"extCID"`

	// ExtID Free rounds ID (external). Used as idempotency key. Same ID can be used to create free rounds only once.
	ExtID string `json:"extID"`

	// GameIDs List of game IDs. If not provided, free rounds will be available for all games.
	GameIDs *[]string `json:"gameIDs,omitempty"`

	// Quantity Number of free rounds.
	Quantity int32 `json:"quantity"`

	// UserIDs List of player IDs (external). If not provided, free rounds will be available for all players.
	UserIDs *[]string `json:"userIDs,omitempty"`

	// ValidFrom Start date when free rounds become available.
	ValidFrom time.Time `json:"validFrom"`

	// ValidUntil End date when free rounds become unavailable. If not provided then this campaign never ends.
	ValidUntil *time.Time `json:"validUntil,omitempty"`
}

// CreateFreeRoundsResponse defines model for CreateFreeRoundsResponse.
type CreateFreeRoundsResponse struct {
	// ExtID Free rounds ID (external). This is provided in the request.
	ExtID string `json:"extID"`

	// Id Free rounds ID (internal).
	Id openapi_types.UUID `json:"id"`
}

// CreateNewGameRequest defines model for CreateNewGameRequest.
type CreateNewGameRequest struct {
	// CID Client's ID. It's provided by Swipe Games and is used as your identifier.
	CID openapi_types.UUID `json:"cID"`

	// Currency Currency code in ISO4217.
	Currency string `json:"currency"`

	// Demo Demo mode. If true, the game will be launched in demo mode (means no callbacks will be fired on your side,
	// and we use our demo balance for the game). If false, the game will be launched in real mode.
	Demo bool `json:"demo"`

	// DepositURL Deposit URL which we could use to open a deposit page for the user. If you don't provide this URL, deposit flow in the game will be disabled.
	DepositURL *string `json:"depositURL,omitempty"`

	// ExtCID External Client's ID (client/platform/game aggregator/integrator or casino on your side). This is provided from your side, and this is
	// how you identify your clients. We use it in all callbacks to you.
	ExtCID string `json:"extCID"`

	// GameID Game's ID. This is Swipe Games's game identifier. See the list of supported games in `Game IDs` section.
	GameID string `json:"gameID"`

	// Locale Locale code in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator.
	Locale string `json:"locale"`

	// Platform Platform code. This is used to identify the platform where the game is launched.
	Platform PlatformType `json:"platform"`

	// ReturnURL Return URL which we could use to redirect the user after the game is finished/exited. If you don't provide this URL, return button in the game will be disabled. Please make sure you provide this URL when using redirect to open the game, otherwise player cannot go back to your site.
	ReturnURL *string `json:"returnURL,omitempty"`

	// SessionID Session ID (external).This is your Session ID. We use it in all callbacks to you.
	// Not required for demo games, since we don't use callbacks for demo games.
	SessionID *string            `json:"sessionID,omitempty"`
	User      *externalRef0.User `json:"user,omitempty"`
}

// CreateNewGameResponse defines model for CreateNewGameResponse.
type CreateNewGameResponse struct {
	GameURL string             `json:"gameURL"`
	GsID    openapi_types.UUID `json:"gsID"`
}

// DeleteFreeRoundsRequest defines model for DeleteFreeRoundsRequest.
type DeleteFreeRoundsRequest struct {
	// CID Client's ID (internal)
	CID openapi_types.UUID `json:"cID"`

	// ExtCID External Client's ID (external)
	ExtCID string `json:"extCID"`

	// ExtID Free rounds ID (external). Used as idempotency key. One of id or extID must be provided.
	ExtID *string `json:"extID,omitempty"`

	// Id Free rounds ID (internal). Used as idempotency key. One of id or extID must be provided.
	Id *openapi_types.UUID `json:"id,omitempty"`
}

// GameInfo defines model for GameInfo.
type GameInfo struct {
	// BetLines List of bet lines supported for this game per currency. Available
	// only if game has free spins. See more info in related section.
	BetLines *[]BetLineInfo `json:"betLines,omitempty"`

	// Currencies List of supported currency codes in ISO 4217 format
	Currencies []string `json:"currencies"`

	// HasFreeSpins If game supports free spins
	HasFreeSpins bool `json:"hasFreeSpins"`

	// Id Game's ID (internal)
	Id     string         `json:"id"`
	Images GameInfoImages `json:"images"`

	// Locales List of supported locales in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator.
	Locales []string `json:"locales"`

	// Platforms List of supported platform types
	Platforms []PlatformType `json:"platforms"`

	// Rtp Game's RTP
	Rtp int `json:"rtp"`

	// Title Game's title in English
	Title string `json:"title"`
}

// GameInfoImages defines model for GameInfoImages.
type GameInfoImages struct {
	// BaseURL Image's base URL
	BaseURL string `json:"baseURL"`

	// Horizontal Path to horizontal image. 4:3 aspect.
	Horizontal string `json:"horizontal"`

	// Square Path to square image. 1:1 aspect.
	Square string `json:"square"`

	// Vertical Path to vertical image. 3:4 aspect.
	Vertical string `json:"vertical"`

	// Widescreen Path to widescreen image. 16:9 aspect.
	Widescreen string `json:"widescreen"`
}

// GamesResponse defines model for GamesResponse.
type GamesResponse = []GameInfo

// PlatformType Platform type where the game can be launched
type PlatformType string

// PostCreateNewGameParams defines parameters for PostCreateNewGame.
type PostCreateNewGameParams struct {
	// XREQUESTSIGN Request signature (see Authentication section for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// DeleteFreeRoundsParams defines parameters for DeleteFreeRounds.
type DeleteFreeRoundsParams struct {
	// XREQUESTSIGN Request signature (see Authentication section for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// PostFreeRoundsParams defines parameters for PostFreeRounds.
type PostFreeRoundsParams struct {
	// XREQUESTSIGN Request signature (see Authentication section for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// GetGamesParams defines parameters for GetGames.
type GetGamesParams struct {
	// CID Client's ID
	CID openapi_types.UUID `form:"cID" json:"cID"`

	// ExtCID External Client's ID
	ExtCID string `form:"extCID" json:"extCID"`

	// XREQUESTSIGN Request signature (see Authentication section for more details)
	XREQUESTSIGN string `json:"X-REQUEST-SIGN"`
}

// PostCreateNewGameJSONRequestBody defines body for PostCreateNewGame for application/json ContentType.
type PostCreateNewGameJSONRequestBody = CreateNewGameRequest

// DeleteFreeRoundsJSONRequestBody defines body for DeleteFreeRounds for application/json ContentType.
type DeleteFreeRoundsJSONRequestBody = DeleteFreeRoundsRequest

// PostFreeRoundsJSONRequestBody defines body for PostFreeRounds for application/json ContentType.
type PostFreeRoundsJSONRequestBody = CreateFreeRoundsRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCreateNewGameWithBody request with any body
	PostCreateNewGameWithBody(ctx context.Context, params *PostCreateNewGameParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCreateNewGame(ctx context.Context, params *PostCreateNewGameParams, body PostCreateNewGameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteFreeRoundsWithBody request with any body
	DeleteFreeRoundsWithBody(ctx context.Context, params *DeleteFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteFreeRounds(ctx context.Context, params *DeleteFreeRoundsParams, body DeleteFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostFreeRoundsWithBody request with any body
	PostFreeRoundsWithBody(ctx context.Context, params *PostFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostFreeRounds(ctx context.Context, params *PostFreeRoundsParams, body PostFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetGames request
	GetGames(ctx context.Context, params *GetGamesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCreateNewGameWithBody(ctx context.Context, params *PostCreateNewGameParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateNewGameRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCreateNewGame(ctx context.Context, params *PostCreateNewGameParams, body PostCreateNewGameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateNewGameRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteFreeRoundsWithBody(ctx context.Context, params *DeleteFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteFreeRoundsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteFreeRounds(ctx context.Context, params *DeleteFreeRoundsParams, body DeleteFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteFreeRoundsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostFreeRoundsWithBody(ctx context.Context, params *PostFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostFreeRoundsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostFreeRounds(ctx context.Context, params *PostFreeRoundsParams, body PostFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostFreeRoundsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetGames(ctx context.Context, params *GetGamesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGamesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCreateNewGameRequest calls the generic PostCreateNewGame builder with application/json body
func NewPostCreateNewGameRequest(server string, params *PostCreateNewGameParams, body PostCreateNewGameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCreateNewGameRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostCreateNewGameRequestWithBody generates requests for PostCreateNewGame with any type of body
func NewPostCreateNewGameRequestWithBody(server string, params *PostCreateNewGameParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/create-new-game")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-REQUEST-SIGN", runtime.ParamLocationHeader, params.XREQUESTSIGN)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

// NewDeleteFreeRoundsRequest calls the generic DeleteFreeRounds builder with application/json body
func NewDeleteFreeRoundsRequest(server string, params *DeleteFreeRoundsParams, body DeleteFreeRoundsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteFreeRoundsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewDeleteFreeRoundsRequestWithBody generates requests for DeleteFreeRounds with any type of body
func NewDeleteFreeRoundsRequestWithBody(server string, params *DeleteFreeRoundsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/free-rounds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-REQUEST-SIGN", runtime.ParamLocationHeader, params.XREQUESTSIGN)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

// NewPostFreeRoundsRequest calls the generic PostFreeRounds builder with application/json body
func NewPostFreeRoundsRequest(server string, params *PostFreeRoundsParams, body PostFreeRoundsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostFreeRoundsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostFreeRoundsRequestWithBody generates requests for PostFreeRounds with any type of body
func NewPostFreeRoundsRequestWithBody(server string, params *PostFreeRoundsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/free-rounds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-REQUEST-SIGN", runtime.ParamLocationHeader, params.XREQUESTSIGN)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

// NewGetGamesRequest generates requests for GetGames
func NewGetGamesRequest(server string, params *GetGamesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/games")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cID", runtime.ParamLocationQuery, params.CID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "extCID", runtime.ParamLocationQuery, params.ExtCID); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-REQUEST-SIGN", runtime.ParamLocationHeader, params.XREQUESTSIGN)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-REQUEST-SIGN", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCreateNewGameWithBodyWithResponse request with any body
	PostCreateNewGameWithBodyWithResponse(ctx context.Context, params *PostCreateNewGameParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateNewGameResponse, error)

	PostCreateNewGameWithResponse(ctx context.Context, params *PostCreateNewGameParams, body PostCreateNewGameJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateNewGameResponse, error)

	// DeleteFreeRoundsWithBodyWithResponse request with any body
	DeleteFreeRoundsWithBodyWithResponse(ctx context.Context, params *DeleteFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteFreeRoundsResponse, error)

	DeleteFreeRoundsWithResponse(ctx context.Context, params *DeleteFreeRoundsParams, body DeleteFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteFreeRoundsResponse, error)

	// PostFreeRoundsWithBodyWithResponse request with any body
	PostFreeRoundsWithBodyWithResponse(ctx context.Context, params *PostFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostFreeRoundsResponse, error)

	PostFreeRoundsWithResponse(ctx context.Context, params *PostFreeRoundsParams, body PostFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostFreeRoundsResponse, error)

	// GetGamesWithResponse request
	GetGamesWithResponse(ctx context.Context, params *GetGamesParams, reqEditors ...RequestEditorFn) (*GetGamesResponse, error)
}

type PostCreateNewGameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateNewGameResponse
	JSON401      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostCreateNewGameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCreateNewGameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteFreeRoundsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *externalRef0.ErrorResponse
	JSON404      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteFreeRoundsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteFreeRoundsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostFreeRoundsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateFreeRoundsResponse
	JSON401      *externalRef0.ErrorResponse
	JSON409      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostFreeRoundsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostFreeRoundsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetGamesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GamesResponse
	JSON401      *externalRef0.ErrorResponse
	JSON404      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetGamesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGamesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostCreateNewGameWithBodyWithResponse request with arbitrary body returning *PostCreateNewGameResponse
func (c *ClientWithResponses) PostCreateNewGameWithBodyWithResponse(ctx context.Context, params *PostCreateNewGameParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateNewGameResponse, error) {
	rsp, err := c.PostCreateNewGameWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateNewGameResponse(rsp)
}

func (c *ClientWithResponses) PostCreateNewGameWithResponse(ctx context.Context, params *PostCreateNewGameParams, body PostCreateNewGameJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateNewGameResponse, error) {
	rsp, err := c.PostCreateNewGame(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateNewGameResponse(rsp)
}

// DeleteFreeRoundsWithBodyWithResponse request with arbitrary body returning *DeleteFreeRoundsResponse
func (c *ClientWithResponses) DeleteFreeRoundsWithBodyWithResponse(ctx context.Context, params *DeleteFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteFreeRoundsResponse, error) {
	rsp, err := c.DeleteFreeRoundsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteFreeRoundsResponse(rsp)
}

func (c *ClientWithResponses) DeleteFreeRoundsWithResponse(ctx context.Context, params *DeleteFreeRoundsParams, body DeleteFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteFreeRoundsResponse, error) {
	rsp, err := c.DeleteFreeRounds(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteFreeRoundsResponse(rsp)
}

// PostFreeRoundsWithBodyWithResponse request with arbitrary body returning *PostFreeRoundsResponse
func (c *ClientWithResponses) PostFreeRoundsWithBodyWithResponse(ctx context.Context, params *PostFreeRoundsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostFreeRoundsResponse, error) {
	rsp, err := c.PostFreeRoundsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostFreeRoundsResponse(rsp)
}

func (c *ClientWithResponses) PostFreeRoundsWithResponse(ctx context.Context, params *PostFreeRoundsParams, body PostFreeRoundsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostFreeRoundsResponse, error) {
	rsp, err := c.PostFreeRounds(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostFreeRoundsResponse(rsp)
}

// GetGamesWithResponse request returning *GetGamesResponse
func (c *ClientWithResponses) GetGamesWithResponse(ctx context.Context, params *GetGamesParams, reqEditors ...RequestEditorFn) (*GetGamesResponse, error) {
	rsp, err := c.GetGames(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGamesResponse(rsp)
}

// ParsePostCreateNewGameResponse parses an HTTP response from a PostCreateNewGameWithResponse call
func ParsePostCreateNewGameResponse(rsp *http.Response) (*PostCreateNewGameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCreateNewGameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateNewGameResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteFreeRoundsResponse parses an HTTP response from a DeleteFreeRoundsWithResponse call
func ParseDeleteFreeRoundsResponse(rsp *http.Response) (*DeleteFreeRoundsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteFreeRoundsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostFreeRoundsResponse parses an HTTP response from a PostFreeRoundsWithResponse call
func ParsePostFreeRoundsResponse(rsp *http.Response) (*PostFreeRoundsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostFreeRoundsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateFreeRoundsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetGamesResponse parses an HTTP response from a GetGamesWithResponse call
func ParseGetGamesResponse(rsp *http.Response) (*GetGamesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGamesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GamesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create new game
	// (POST /create-new-game)
	PostCreateNewGame(ctx echo.Context, params PostCreateNewGameParams) error
	// Cancel/Delete free rounds campaign
	// (DELETE /free-rounds)
	DeleteFreeRounds(ctx echo.Context, params DeleteFreeRoundsParams) error
	// Create new free rounds campaign
	// (POST /free-rounds)
	PostFreeRounds(ctx echo.Context, params PostFreeRoundsParams) error
	// Get Games' Information
	// (GET /games)
	GetGames(ctx echo.Context, params GetGamesParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostCreateNewGame converts echo context to params.
func (w *ServerInterfaceWrapper) PostCreateNewGame(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostCreateNewGameParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCreateNewGame(ctx, params)
	return err
}

// DeleteFreeRounds converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteFreeRounds(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFreeRoundsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteFreeRounds(ctx, params)
	return err
}

// PostFreeRounds converts echo context to params.
func (w *ServerInterfaceWrapper) PostFreeRounds(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostFreeRoundsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostFreeRounds(ctx, params)
	return err
}

// GetGames converts echo context to params.
func (w *ServerInterfaceWrapper) GetGames(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGamesParams
	// ------------- Required query parameter "cID" -------------

	err = runtime.BindQueryParameter("form", true, true, "cID", ctx.QueryParams(), &params.CID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cID: %s", err))
	}

	// ------------- Required query parameter "extCID" -------------

	err = runtime.BindQueryParameter("form", true, true, "extCID", ctx.QueryParams(), &params.ExtCID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter extCID: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-REQUEST-SIGN" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-REQUEST-SIGN")]; found {
		var XREQUESTSIGN string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-REQUEST-SIGN, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-REQUEST-SIGN", valueList[0], &XREQUESTSIGN, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-REQUEST-SIGN: %s", err))
		}

		params.XREQUESTSIGN = XREQUESTSIGN
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-REQUEST-SIGN is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGames(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/create-new-game", wrapper.PostCreateNewGame)
	router.DELETE(baseURL+"/free-rounds", wrapper.DeleteFreeRounds)
	router.POST(baseURL+"/free-rounds", wrapper.PostFreeRounds)
	router.GET(baseURL+"/games", wrapper.GetGames)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbe2/buLL/KoTuBdoC8itx0o3/a5O28EVvm5vH3XNOWziUNJa5kUiVpOL4LPrdD4ak",
	"XjbtOLstTnOwwGJrSRQ5M5z5zW+Gyu9BLPJCcOBaBZPfAxUvIKfm52vQ7xmHKZ8LvCykKEBqBuZhXEoJ",
	"PF7h7wRULFmhmeDBJDh1T0gsEiCMk+nlx/HB6GUQBnBP8yKDYBJcX54FYaBXBV4oLRlPg29hcEez0s7f",
	"nfM9U5qIOYlAk4xxIHYgeT7sMZ7APSSESklXJKeFIlqQUS+iCpL6BfWi/5kHYcA05Gb+/5YwDybBfw0a",
	"9QdO94FT/P9xDZTKiWlWCL59CwMJX0smIQkmnxpD1NJ/qd8Q0W8Qa5yiM+WGMXN6/xr0ptr/S+9ZXuZG",
	"C5qLkmsyF5LoBVPWDM8ZJ5UApORMqxcdM4/6w6HPzjm9PxUwn29fMi8zzYqMgSS0wH8TNKteAArTWePI",
	"u8aalZyGrZV9VjqVQDW8lQAXouSJuoCvJSi9abDImnNT/A9lHoHsuEos+JylpYSkMV5KcxgUUtyxBGS/",
	"rc7BMAzmQuZUB5OAcX14YIVGowSTk5MwyBm3F6NaA8Y1pCBRhXh65gmJjAHXzxSZnuGWaZCcZrhT9Upl",
	"yRLfRv2YMIN7feqT8829FY10BEZjEZqmElKqhSRCkpgqxkXX11ailDO41zO/JnCvfUviZhNpdtssBk6E",
	"F31yjQFMFWEJ5IXQRtlbWPXJJQo0PSMx5SQCUirrnLHxHjJvzSh4tiKCx2CjvxEWB83soC3yotbTsx1Y",
	"lFopVJ9M54QLTZw/JWFHhCXLMpSS3lGW0SgD44U0y8wEquN8nwKVzmKq48XsBDdSpTO1ZAXg1ZcWeG0I",
	"20WoMPhaUq6ZXu0KkJaQHSFGfzICSgVyp+GKjK5Aouk62/0HrWhnW7ejvTs6OAxC93t8dPw4G97RjCVv",
	"pcg3NbnUVGqSoLctF8A7kkYQi7wlaEew4GB4cNwbjnrD0dVwODH/9YfD4T/aWIDz9jTLYUuGZMk11yzz",
	"hC9PdgtV8kasdXsjtnOLjjHNC8pSTjjcgSSAHrIWP1aPg97BL1cHh5Ojk8nRSf/k5GRfPdZz6PQsqBCi",
	"RqewnVprhw5r7G/v0H7JRBWCK0/6fTw0XaGZmGqMx7jJjdImrL5v51jy8BJ1bug/nBzWbGiGWE22W+MD",
	"LN/RHLbm1YeyV59M8UetdrQilwhQBGdVhPIErVI64MaMgOjNNZszkNaHfkDK6++T8xLIxeaUZ5ALkovE",
	"xoOWJYRmIw24V6CT0ZLHC7vLSfUCeZ4D5YpwQWKaZRGNbxuYmuOuEMGtCRRLIPzM0TpLk64I3jUzRTSj",
	"PAbHTOy6FgvnNFMPCSOBZlZ6Y1qncyREBpRbpQuhmL6+eO9T3Twj1xfvyXLB4gUKF4syS4yIWhBRACeU",
	"uElIQdNGUER5I+dKlCQR/FmNJBZDri/eh/Wb80wsqxDpKJMwhWCUdHdwoXWhJoMBGq+nmIZ+LPKBm+zP",
	"85nYXAyKjGp0xsEavxmYXCa7VKezlz4AmEuRt3bbhIK2gz7zhVgaO7lYWNmBVg7VJ79ap2AabYQ5rXEo",
	"LXDsOvo+QLUsddk0BwapC+NK/lb0PrO0uB2w5BLAbFrmUrcqi0JIDYklLyjvzTvHg26IghhXWpe2y2k2",
	"pM1ETDMPlX9v7jex/ubqLXl9ek7GL4nFEPJ8evmRHB+e9EYkozwt0T/N8CXTCyLMRDRDlCCHo+Pj3gjd",
	"m2tpAeRFSErFeEpKnoBUsZCAoKWgoGbzuz4JfFYqn/iVG6ECNMs+zoPJp93l5bl74wqn+vYlXNO7emyE",
	"bHaqYrm1D+G+VItjxpfQxBfWhw4numokoG61KAKTPHQpuRcaLsyjHcggIWESYl1DAaFzDbIjwJxxphaQ",
	"DOCeaUgeBAsrD4lKrQXfjRbkPAOqgOT0FogqJZiJ16e0NMjucSOwg7Vq8pAIvQC5ZAoqYhpTjsQoRXSO",
	"b10IYlxr2AencNZeJqJo5XMXBUoxwX3heWkfrXGNav+NDM2Q/VDjg9CkIgkGuk3SMbEbEsUw8yzB7QhO",
	"1kzRHbwe0nQUHcSHybgHR/Pj3stfToY9GsVJD+ajg8Px0THe8WmPrvJQ94UWbHY36g9nschzwXvNkNk1",
	"vr6VPFrS6MDPJfxWfHb4pAOdPZjSNtKI67jg2QRgZff3cQyumtG975PtDDLYq0HyndsQj0uwtfP+4D7A",
	"Rw6YlFiCedrMS/JSaYSKKi93iNEf5eLfQYLHeULHpX1+gK7p78u66miPHqpqZfNOY4wUCIIuVvrkVVUy",
	"fuamncJc62NBla0xVcG4slwhxyTK+FxYdppRnLxDCx7TgDUaeipzJxvbpWWjW9yuGpQrGwjWDY5HdDsH",
	"tnx4c30RhMG71+eP6xksqEI3ukSLbMo2dZZzsrXN15bBVCEeMu9z2prSdQN6b/LFcprCg/tRudvUjq5J",
	"2172d0P//RzuU03iAP9X6FkkH7e9VS7ZS++am+EsqitIRcPCIBcRs4lor8jocsdNCaUutjrJxdV5W4qT",
	"l77unWbaR8bdFOYp7uQbnmZMLTqudop+Rnx+tgZvdo3QtiwqT+qEde2YbZuvhZdVdhc6TmvnXsNIqsDL",
	"e80LzxTBAcSm4k22Fye8b7qylhkxMbCyDh4ItYWQ7J+Ca+rp3J1TvUDW1owhZtI+GU8OCVUFxLrLPQfN",
	"0H7BUy/V/FpSCdsXs8+rhUaTkX8hO2zbIndo1niXTtWIaqHDydi/UDVw21JLZhYA4NsXa8bUeh1PTvzr",
	"NWP9K655beU1tWE7W9oRr2WWbf7ZaUfuFfp1zveEfQcWNo3TRqL1UtEdolTlIpqIl/k2kNrYlB1s/Y2U",
	"QrbVXIMU4CBpRgCHEenGGSrS7imel1HGYvLqfIo8rKRZtrK1MA5sHtYTuFpljQ6LxCOBEdCW2S210Soz",
	"LvRsjlywVTaYmzW+19C1cZvGJkXNokzEt+ZOBHqWsdw0rzKhVH2hWQ71BeOqnM9ZjEx6NkceGtT14gzu",
	"C+OIzZ2OiIZ+z2LBuSVbM2NV744loCnLPCnsCuIFN5HqhtTNPjNZn5yaFkB14mYrxKhMU8bTkKiFeYqV",
	"cwR4teTVibGtq71N8RyUoqlnb16RSDKYk9ZdTK+1NK0k1BJsv2XXz6adDL5QfagY3Sy8LDvxFF8t2tKm",
	"MzQrFrR34LXOnEmlP9AcvOzExwdRqGdbjyuap+12pnfpjO5YmbP4dsvDzVOJTbPiIOaqlzUXdILi9p0i",
	"mcPI3oUI07qTpAjwpBCMa9U6DOawrNodOeWmgd0q86qDLmX7tVi9uILRsqCgvayRp1nbgryyco/6o/4Q",
	"LSMK4LRgwSQ47A/75vSR6oXxjIEVqcdh2Uud8QqhtHcTbTXmjpNa+tBaI6O7hJQpDVKZ2zcJ5OIGS9Eb",
	"CTS7sQAvbLNLgbwDafS0nTZr5fcW9yXSnc+8fQzRJ38XpUkPm90+E2Guy4ZMwpyHYrwhF69Ti5C212Zb",
	"VOytxFmNfTFiKGo7TTA/CaU7XRdjNhyNqpl+6np/0tpFsZRTXUogzxUAeVXqBXDMuwYuXN1p/McUpg7W",
	"XhisRUYHNAEZhAE32xH8rXfx5v+u31xe9S6n7z4EbU+2NZlNxT6v/2IHg9KvRbKyQMA1cLO75gMaK9Tg",
	"NyV4853VQznfe2pn4sdvkEgkq7oDoYAbw//P5ccPuI/CgntVeD3SYl1bmDB3CReVOBgOf5TSjj94tBa3",
	"GHLj4ei7Lb03m/FI86sUPG25pJAGvW7BMLSj72igPyPlpYUBm0NFbLhNYmBblXlOMXO5DmiNNIiHNMU4",
	"DCxaGEAMvuBLA4TTnoVTC2QZaE86P6U8hmxg+5cE7pnSCBU+MG5wJzYveQbxlCSlrLCm/lyhAMlEEtqz",
	"A/Mdg4LPnGYZuWG8V0iRSlDqxvthCW4M4yUkIYlKTbgw6vtGGrCr+npdIFtvz/6FY85jt/Wtf2Ioe7pQ",
	"Mx6Ofwop33qC29QHtmp5aqDYQTAfcLVw0qjuMODLt3ALz2vh7Jb5NnnSX+CyhS88KXD5QXr/Z1Cl8fDk",
	"58UvmkmgycpSGPWEmd2jEAyZnimjzcm3708V3oE2B38YMxgaNBKlXv9eaAPR3oF+5x48MSwLdxyud/88",
	"4mgIv4yHwx4cnES98SgZ9+jL0XFvPD4+Pjoaj4dD8+cTRr6vJchVI549Bt4u04PH9ve9VPTcZKfTs2BT",
	"at8B/o5PzXxS1l9e7G28rmDufZsdfhBUdjvuTx4ffw5+Z9tiT5bQIWLZDx/JtAGuFgTWAxAAzadbOKkP",
	"ni41TasOWxAGpcxa54VK05TxtF8dZPaHa8eHtGCDu5EnOM+lSMrYQZt37kKKpJl4tGXiL9/+FQAA//9w",
	"c8Uw5jcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../common-components.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
