/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Swipe Games Core Public API
 * This is the Core API for Swipe Games Public API. It provides endpoints to create new games, manage free rounds campaigns, and more.

 * OpenAPI spec version: 1.2.17
 */
/**
 * Platform type where the game can be launched
 */
export type PlatformType = typeof PlatformType[keyof typeof PlatformType];


export const PlatformType = {
  desktop: 'desktop',
  mobile: 'mobile',
} as const;

export interface User {
  /** User's ID (external). This is User's ID on your side. */
  id: string;
  firstName?: string;
  lastName?: string;
  nickName?: string;
  /** Country code ISO 3166-1 alpha-2. */
  country?: string;
}

export interface CreateNewGameRequest {
  /** Client's ID. It's provided by Swipe Games and is used as your identifier.
 */
  cID: string;
  /** External Client's ID (client/platform/game aggregator/integrator or casino on your side). This is provided from your side, and this is
how you identify your clients. We use it in all callbacks to you.
 */
  extCID: string;
  /** Game's ID. This is Swipe Games's game identifier. See the list of supported games in `Game IDs` section.
 */
  gameID: string;
  /** Session ID (external).This is your Session ID. We use it in all callbacks to you.
Not required for demo games, since we don't use callbacks for demo games.
 */
  sessionID?: string;
  /** Return URL which we could use to redirect the user after the game is finished/exited. If you don't provide this URL, return button in the game will be disabled. Please make sure you provide this URL when using redirect to open the game, otherwise player cannot go back to your site. */
  returnURL?: string;
  /** Deposit URL which we could use to open a deposit page for the user. If you don't provide this URL, deposit flow in the game will be disabled. */
  depositURL?: string;
  /** Currency code in ISO4217. */
  currency: string;
  /** Locale code in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator. */
  locale: string;
  /** Platform code. This is used to identify the platform where the game is launched. */
  platform: PlatformType;
  /** Demo mode. If true, the game will be launched in demo mode (means no callbacks will be fired on your side,
and we use our demo balance for the game). If false, the game will be launched in real mode.
 */
  demo: boolean;
  /** Initial demo balance for the user (in currency units). Only used in demo mode, ignored in real mode.
Must be greater than the minimum bet. Default is 10 000 USD equivalent.
 */
  initDemoBalance?: string;
  user?: User;
}

export interface CreateNewGameResponse {
  gameURL: string;
  gsID: string;
}

export interface CreateFreeRoundsRequest {
  /** Free rounds ID (external). Used as idempotency key. Same ID can be used to create free rounds only once.
 */
  extID: string;
  /** Client's ID (internal) */
  cID: string;
  /** External Client's ID (game aggregator or casino) */
  extCID: string;
  /** List of game IDs. If not provided, free rounds will be available for all games. */
  gameIDs?: string[];
  /** List of player IDs (external). If not provided, free rounds will be available for all players. */
  userIDs?: string[];
  /** Currency code in ISO4217 */
  currency: string;
  /**
   * Number of free rounds.
   * @minimum 1
   * @maximum 99
   */
  quantity: number;
  /**
   * Number of bet line configured for this game/provider. You can find more information in related section
[Free Rounds Bet Lines](/public-api/free-rounds-bet-lines).

   * @minimum 1
   * @maximum 99
   */
  betLine: number;
  /** Start date when free rounds become available. */
  validFrom: string;
  /** End date when free rounds become unavailable. If not provided then this campaign never ends.
If you provide finite validity duration, it should not exceed 30 days.
 */
  validUntil?: string;
}

export interface CreateFreeRoundsResponse {
  /** Free rounds ID (internal). */
  id: string;
  /** Free rounds ID (external). This is provided in the request. */
  extID: string;
}

export interface DeleteFreeRoundsRequest {
  /** Free rounds ID (internal). Used as idempotency key. One of id or extID must be provided.
 */
  id?: string;
  /** Free rounds ID (external). Used as idempotency key. One of id or extID must be provided.
 */
  extID?: string;
  /** Client's ID (internal) */
  cID: string;
  /** External Client's ID (external) */
  extCID: string;
}

export interface GameInfoImages {
  /** Image's base URL */
  baseURL: string;
  /** Path to square image. 1:1 aspect. */
  square: string;
  /** Path to horizontal image. 4:3 aspect. */
  horizontal: string;
  /** Path to widescreen image. 16:9 aspect. */
  widescreen: string;
  /** Path to vertical image. 3:4 aspect. */
  vertical: string;
}

export interface BetLineValue {
  /** Maximum bet amount for this line (in currency units) */
  maxBet: string;
  /** Maximum multiplier applied to the bet */
  maxCoeff: string;
}

export interface BetLineInfo {
  /** Currency code in ISO4217 */
  currency: string;
  /** List of bet line values (0-indexed array maps to 1-based bet lines).
 */
  values: BetLineValue[];
}

export interface GameInfo {
  /** Game's title in English */
  title: string;
  /** Game's ID (internal) */
  id: string;
  /** List of supported locales in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator. */
  locales: string[];
  /** List of supported currency codes in ISO 4217 format */
  currencies: string[];
  /** List of supported platform types */
  platforms: PlatformType[];
  /** Image URLs for the game */
  images: GameInfoImages;
  /** If game supports free spins */
  hasFreeSpins: boolean;
  /** Game's RTP */
  rtp: number;
  /** List of bet lines supported for this game per currency. Available
only if game has free spins. See more info in related section [Free Rounds Bet Lines](/public-api/free-rounds-bet-lines).
 */
  betLines?: BetLineInfo[];
}

export type GamesResponse = GameInfo[];

/**
 * Error code.
 */
export type ErrorResponseCode = typeof ErrorResponseCode[keyof typeof ErrorResponseCode];


export const ErrorResponseCode = {
  game_not_found: 'game_not_found',
  currency_not_supported: 'currency_not_supported',
  locale_not_supported: 'locale_not_supported',
  account_blocked: 'account_blocked',
  bet_limit: 'bet_limit',
  loss_limit: 'loss_limit',
  time_limit: 'time_limit',
  insufficient_funds: 'insufficient_funds',
  session_expired: 'session_expired',
  session_not_found: 'session_not_found',
  client_connection_error: 'client_connection_error',
} as const;

/**
 * General error response for Swipe Games Public API. Usually used for Public API responses.

 */
export interface ErrorResponse {
  /** A brief description of the error in English. Could be shown to the player. */
  message: string;
  /** Technical details for the error. Could be used for debugging, should not be shown to the player. */
  details?: string;
  /** Error code. */
  code?: ErrorResponseCode;
}

export type GetGamesParams = {
/**
 * Client's ID
 */
cID: string;
/**
 * External Client's ID
 */
extCID: string;
};

/**
 * Use this request to create a new game. It registers new `demo` or `real` game on the server and returns the Launcher URL
for the game. You can redirect the user to this URL to start playing the game or open it in iFrame.

 * @summary Create new game
 */
export type postCreateNewGameResponse200 = {
  data: CreateNewGameResponse
  status: 200
}

export type postCreateNewGameResponse401 = {
  data: ErrorResponse
  status: 401
}

export type postCreateNewGameResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postCreateNewGameResponseSuccess = (postCreateNewGameResponse200) & {
  headers: Headers;
};
export type postCreateNewGameResponseError = (postCreateNewGameResponse401 | postCreateNewGameResponse500) & {
  headers: Headers;
};

export type postCreateNewGameResponse = (postCreateNewGameResponseSuccess | postCreateNewGameResponseError)

export const getPostCreateNewGameUrl = () => {


  

  return `/create-new-game`
}

export const postCreateNewGame = async (createNewGameRequest: CreateNewGameRequest, options?: RequestInit): Promise<postCreateNewGameResponse> => {
  
  const res = await fetch(getPostCreateNewGameUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createNewGameRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postCreateNewGameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postCreateNewGameResponse
}
  


/**
 * Create new free rounds campaign
 * @summary Create new free rounds campaign
 */
export type postFreeRoundsResponse200 = {
  data: CreateFreeRoundsResponse
  status: 200
}

export type postFreeRoundsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type postFreeRoundsResponse409 = {
  data: ErrorResponse
  status: 409
}

export type postFreeRoundsResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postFreeRoundsResponseSuccess = (postFreeRoundsResponse200) & {
  headers: Headers;
};
export type postFreeRoundsResponseError = (postFreeRoundsResponse401 | postFreeRoundsResponse409 | postFreeRoundsResponse500) & {
  headers: Headers;
};

export type postFreeRoundsResponse = (postFreeRoundsResponseSuccess | postFreeRoundsResponseError)

export const getPostFreeRoundsUrl = () => {


  

  return `/free-rounds`
}

export const postFreeRounds = async (createFreeRoundsRequest: CreateFreeRoundsRequest, options?: RequestInit): Promise<postFreeRoundsResponse> => {
  
  const res = await fetch(getPostFreeRoundsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createFreeRoundsRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postFreeRoundsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postFreeRoundsResponse
}
  


/**
 * Cancel/Delete existing free rounds campaign. You can cancel free rounds campaing during the campaign period, in this case
all `in-progress` free rounds will be continued, but no new free rounds will be started.

 * @summary Cancel/Delete free rounds campaign
 */
export type deleteFreeRoundsResponse200 = {
  data: void
  status: 200
}

export type deleteFreeRoundsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteFreeRoundsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteFreeRoundsResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteFreeRoundsResponseSuccess = (deleteFreeRoundsResponse200) & {
  headers: Headers;
};
export type deleteFreeRoundsResponseError = (deleteFreeRoundsResponse401 | deleteFreeRoundsResponse404 | deleteFreeRoundsResponse500) & {
  headers: Headers;
};

export type deleteFreeRoundsResponse = (deleteFreeRoundsResponseSuccess | deleteFreeRoundsResponseError)

export const getDeleteFreeRoundsUrl = () => {


  

  return `/free-rounds`
}

export const deleteFreeRounds = async (deleteFreeRoundsRequest: DeleteFreeRoundsRequest, options?: RequestInit): Promise<deleteFreeRoundsResponse> => {
  
  const res = await fetch(getDeleteFreeRoundsUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteFreeRoundsRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteFreeRoundsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteFreeRoundsResponse
}
  


/**
 * Get information about supported games
 * @summary Get Games' Information
 */
export type getGamesResponse200 = {
  data: GamesResponse
  status: 200
}

export type getGamesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGamesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getGamesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getGamesResponseSuccess = (getGamesResponse200) & {
  headers: Headers;
};
export type getGamesResponseError = (getGamesResponse401 | getGamesResponse404 | getGamesResponse500) & {
  headers: Headers;
};

export type getGamesResponse = (getGamesResponseSuccess | getGamesResponseError)

export const getGetGamesUrl = (params: GetGamesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/games?${stringifiedParams}` : `/games`
}

export const getGames = async (params: GetGamesParams, options?: RequestInit): Promise<getGamesResponse> => {
  
  const res = await fetch(getGetGamesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getGamesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getGamesResponse
}
