openapi: 3.0.3
info:
  title: Swipe Games Core Public API
  description: |
    This is the Core API for Swipe Games Public API. It provides endpoints to create new games, manage free rounds campaigns, and more.
  version: 1.1.2

servers:
  - url: https://staging.platform.0.swipegames.io/api/v1
    description: Stage server
  - url: https://prod.platform.1.swipegames.io/api/v1
    description: Production server

paths:
  /create-new-game:
    post:
      summary: Create new game
      tags:
        - Launch Game
      description: |
        Use this request to create a new game. It registers new `demo` or `real` game on the server and returns the Launcher URL
        for the game. You can redirect the user to this URL to start playing the game or open it in iFrame.
      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (see Authentication section for more details)
          schema:
            type: string
      requestBody:
        required: true
        description: Request body must be sent in JSON canonical format (see Authentication section for more details)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNewGameRequest"
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateNewGameResponse"

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"
  /free-rounds:
    post:
      summary: Create new free rounds campaign
      tags:
        - Free Rounds
      description: Create new free rounds campaign
      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (see Authentication section for more details)
          schema:
            type: string

      requestBody:
        required: true
        description: Request body must be sent in JSON canonical format (see Authentication section for more details)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFreeRoundsRequest"

      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateFreeRoundsResponse"

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        409:
          description: Free rounds campaign already exists
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

    delete:
      summary: Cancel/Delete free rounds campaign
      tags:
        - Free Rounds
      description: |
        Cancel/Delete existing free rounds campaign. You can cancel free rounds campaing during the campaign period, in this case
        all `in-progress` free rounds will be continued, but no new free rounds will be started.

      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (see Authentication section for more details)
          schema:
            type: string

      requestBody:
        required: true
        description: Request body must be sent in JSON canonical format (see Authentication section for more details)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteFreeRoundsRequest"

      responses:
        200:
          description: ok

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        404:
          description: Free rounds campaign not found
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

  /games:
    get:
      tags:
        - Get Games
      summary: Get Games' Information
      description: Get information about supported games
      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (see Authentication section for more details)
          schema:
            type: string
        - name: cID
          in: query
          required: true
          description: Client's ID
          x-go-name: CID
          schema:
            type: string
            format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        - name: extCID
          in: query
          required: true
          description: External Client's ID
          x-go-name: extCID
          schema:
            type: string
          example: your_ext_id

      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GamesResponse"

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        404:
          description: Games not found
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

components:
  schemas:
    PlatformType:
      type: string
      description: Platform type where the game can be launched
      enum:
        - desktop
        - mobile

    CreateNewGameRequest:
      type: object
      required:
        - cID
        - extCID
        - gameID
        - demo
        - platform
        - currency
        - locale
      properties:
        cID:
          description: |
            Client's ID. It's provided by Swipe Games and is used as your identifier.
          type: string
          format: uuid
        extCID:
          description: |
            External Client's ID (client/platform/game aggregator/integrator or casino on your side). This is provided from your side, and this is
            how you identify your clients. We use it in all callbacks to you.
          type: string
          example: your_ext_id
        gameID:
          description: |
            Game's ID. This is Swipe Games's game identifier. See the list of supported games in `Game IDs` section.
          type: string
          example: sg_catch_97
        sessionID:
          description: |
            Session ID (external).This is your Session ID. We use it in all callbacks to you.
            Not required for demo games, since we don't use callbacks for demo games.
          type: string
          example: a1b2c3d4-e5f6-7890-abcd-ef1234567890
        returnURL:
          description: Return URL which we could use to redirect the user after the game is finished/exited.
            If you don't provide this URL, return button in the game will be disabled. Please make sure you provide this URL
            when using redirect to open the game, otherwise player cannot go back to your site.
          type: string
          example: https://your-site.com/game-lobby
        depositURL:
          description: Deposit URL which we could use to open a deposit page for the user.
            If you don't provide this URL, deposit flow in the game will be disabled.
          type: string
          example: https://your-site.com/deposit
        currency:
          description: Currency code in ISO4217.
          type: string
          example: USD
        locale:
          description: Locale code in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator.
          type: string
          example: en_us
        platform:
          description: Platform code. This is used to identify the platform where the game is launched.
          allOf:
            - $ref: "#/components/schemas/PlatformType"
          example: desktop
        demo:
          description: |
            Demo mode. If true, the game will be launched in demo mode (means no callbacks will be fired on your side,
            and we use our demo balance for the game). If false, the game will be launched in real mode.
          type: boolean
        user:
          description: |
            User information we show in the game. User should be provided for real game.
          x-go-type: User
          $ref: "../common-components.yaml#/components/schemas/User"

    CreateNewGameResponse:
      type: object
      required:
        - gameURL
        - gsID
      properties:
        gameURL:
          type: string
        gsID:
          type: string
          format: uuid
    CreateFreeRoundsRequest:
      type: object
      required:
        - cID
        - extID
        - extCID
        - currency
        - quantity
        - betLine
        - validFrom
      properties:
        extID:
          description: |
            Free rounds ID (external). Used as idempotency key. Same ID can be used to create free rounds only once.
          type: string
          example: free_rounds_id
        cID:
          description: Client's ID (internal)
          type: string
          format: uuid
        extCID:
          description: External Client's ID (game aggregator or casino)
          type: string
          example: your_ext_id
        gameIDs:
          description: List of game IDs. If not provided, free rounds will be available for all games.
          type: array
          items:
            type: string
          example: ["sg_catch_97", "sg_swipe_97"]
        userIDs:
          description: List of player IDs (external). If not provided, free rounds will be available for all players.
          type: array
          items:
            type: string
          example: ["player123", "player456"]

        currency:
          description: Currency code in ISO4217
          type: string
          example: USD

        quantity:
          description: Number of free rounds.
          type: integer
          format: int32
          minimum: 1
          maximum: 99
          example: 10

        betLine:
          description: |
            Number of bet line configured for this game/provider. You can find more information in related section
            [Free Rounds Bet Lines](/public-api/free-rounds-bet-lines).
          type: integer
          format: int32
          minimum: 1
          maximum: 99
          example: 20

        validFrom:
          description: Start date when free rounds become available.
          type: string
          format: date-time
          example: "2026-01-01T00:00:00.000Z"

        validUntil:
          description: |
            End date when free rounds become unavailable. If not provided then this campaign never ends.
          type: string
          format: date-time
          example: "2026-02-28T23:59:59.999Z"

    CreateFreeRoundsResponse:
      type: object
      required:
        - id
        - extID
      properties:
        id:
          description: Free rounds ID (internal).
          type: string
          format: uuid

        extID:
          description: Free rounds ID (external). This is provided in the request.
          type: string

    DeleteFreeRoundsRequest:
      type: object
      required:
        - cID
        - extCID
      properties:
        id:
          description: |
            Free rounds ID (internal). Used as idempotency key. One of id or extID must be provided.
          type: string
          format: uuid

        extID:
          description: |
            Free rounds ID (external). Used as idempotency key. One of id or extID must be provided.
          type: string

        cID:
          description: Client's ID (internal)
          type: string
          format: uuid

        extCID:
          description: External Client's ID (external)
          type: string

    GameInfoImages:
      type: object
      required:
        - baseURL
        - square
        - horizontal
        - widescreen
        - vertical
      properties:
        baseURL:
          description: Image's base URL
          type: string
          example: https://cdn.swipegames.io/images/sg_catch_97
        square:
          description: Path to square image. 1:1 aspect.
          type: string
          example: /square.png
        horizontal:
          description: Path to horizontal image. 4:3 aspect.
          type: string
          example: /horizontal.png
        widescreen:
          description: Path to widescreen image. 16:9 aspect.
          type: string
          example: /widescreen.png
        vertical:
          description: Path to vertical image. 3:4 aspect.
          type: string
          example: /vertical.png

    BetLineValue:
      type: object
      required:
        - maxBet
        - maxCoeff
      properties:
        maxBet:
          description: Maximum bet amount for this line (in currency units)
          type: string
          example: "1.00"
        maxCoeff:
          description: Maximum multiplier applied to the bet
          type: string
          example: "5.00"

    BetLineInfo:
      type: object
      required:
        - currency
        - values
      properties:
        currency:
          description: Currency code in ISO4217
          type: string
          example: USD
        values:
          description: |
            List of bet line values (0-indexed array maps to 1-based bet lines).

          type: array
          items:
            $ref: "#/components/schemas/BetLineValue"

    GameInfo:
      type: object
      required:
        - title
        - id
        - locales
        - currencies
        - images
        - platforms
        - hasFreeSpins
        - rtp
      properties:
        title:
          description: Game's title in English
          type: string
          example: Catch 97
        id:
          description: Game's ID (internal)
          type: string
          example: sg_catch_97
        locales:
          description: List of supported locales in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator.
          type: array
          items:
            type: string
          example: ["en_us", "es", "pt_br"]
        currencies:
          description: List of supported currency codes in ISO 4217 format
          type: array
          items:
            type: string
          example: ["USD", "EUR", "GBP"]
        platforms:
          description: List of supported platform types
          type: array
          items:
            $ref: "#/components/schemas/PlatformType"
          example: ["desktop", "mobile"]
        images:
          description: Image URLs for the game
          $ref: "#/components/schemas/GameInfoImages"
        hasFreeSpins:
          description: If game supports free spins
          type: boolean
          example: true
        rtp:
          description: Game's RTP
          type: integer
          example: 97
        betLines:
          description: |
            List of bet lines supported for this game per currency. Available
            only if game has free spins. See more info in related section [Free Rounds Bet Lines](/public-api/free-rounds-bet-lines).
          type: array
          items:
            $ref: "#/components/schemas/BetLineInfo"

    GamesResponse:
      type: array
      items:
        $ref: "#/components/schemas/GameInfo"
