openapi: 3.0.3
info:
  title: Swipe Games Public Core API
  description: |
    This is the core API for Swipe Games Public API. It provides endpoints to create new games, manage free rounds campaigns, and more.
  version: 1.0.0

paths:
  /create-new-game:
    post:
      summary: Create new game
      tags:
        - Launch Game
      description: |
        Use this request to create a new game. It registers new `demo` or `real` game on the server and returns the Launcher URL
        for the game. You can redirect the user to this URL to start playing the game or open it in iFrame.
        Read more about Launcher URL in the [Launcher URL](#laucher-url) section.

      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (read more in the Authentication section)
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNewGameRequest"

      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateNewGameResponse"

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"
  /free-rounds:
    post:
      summary: Create new free rounds campaign
      tags:
        - Free Rounds
      description: Create new free rounds campaign
      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (read more in the Authentication section)
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFreeRoundsRequest"

      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateFreeRoundsResponse"

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        409:
          description: Free rounds campaign already exists
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

    delete:
      summary: Cancel/Delete free rounds campaign
      tags:
        - Free Rounds
      description: |
        Cancel/Delete existing free rounds campaign. You can cancel free rounds campaing during the campaign period, in this case
        all `in-progress` free rounds will be continued, but no new free rounds will be started.

      parameters:
        - name: X-REQUEST-SIGN
          in: header
          required: true
          description: Request signature (read more in the Authentication section)
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteFreeRoundsRequest"

      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteFreeRoundsRes"

        401:
          description: Wrong signature or API key
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        404:
          description: Free rounds campaign not found
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

        500:
          description: Server error occurred
          content:
            application/json:
              schema:
                $ref: "../common-components.yaml#/components/schemas/ErrorResponse"

components:
  schemas:
    CreateNewGameRequest:
      type: object
      required:
        - cID
        - extCID
        - gameID
        - demo
        - returnURL
        - platform
        - currency
        - locale
      properties:
        cID:
          description: |
            Client's ID. It's provided by Swipe Games and is used as your identifier.
          type: string
          format: uuid
        extCID:
          description: |
            External Client's ID (client/platform/game aggregator/integrator or casino on your side). This is provided from your side, and this is
            how you identify your clients. We use it in all callbacks to you.
          type: string
        gameID:
          description: |
            Game's ID. This is Swipe Games's game identifier. See the list of supported games in `Game IDs` section.
          type: string
        sessionID:
          description: |
            Session ID (game integrator or casino).This is your Session ID. We use
            it in all callbacks to you. Not required for demo games, since we don't use callbacks for demo games.
          type: string
        returnURL:
          description: Return URL which we could use to redirect the user after the game is finished/exited.
            If you don't provide this URL, return button in the game will be disabled. Please make sure you provide this URL
            when using redirect to open the game, otherwise player cannot
          type: string
        currency:
          description: Currency code in ISO4217.
          type: string
        locale:
          description: Locale code in IIETF BCP 47 (ISO 639).
          type: string
        platform:
          description: Platform code. This is used to identify the platform where the game is launched.
          type: string
          enum:
            - desktop
            - mobile
        demo:
          description: |
            Demo mode. If true, the game will be launched in demo mode (means no callbacks will be fired on your side,
            and we use our demo balance for the game). If false, the game will be launched in real mode.
          type: boolean
        user:
          description: |
            User information we show in the game. User should be provided for real game.
          x-go-type: User
          $ref: "../common-components.yaml#/components/schemas/User"

    CreateNewGameResponse:
      type: object
      required:
        - gameURL
        - gameSessionID
      properties:
        gameURL:
          type: string
        gameSessionID:
          type: string
          format: uuid
    CreateFreeRoundsRequest:
      type: object
      required:
        - cID
        - extID
        - extCID
        - currency
        - quantity
        - betLine
        - validFrom
      properties:
        extID:
          description: |
            Free rounds ID (external). Used as idempotency key. Same ID can be used to create free rounds only once.
          type: string
        cID:
          description: Client's ID (internal)
          type: string
          format: uuid
        extCID:
          description: External Client's ID (game aggregator or casino)
          type: string
        gameIDs:
          description: List of game IDs. If not provided, free rounds will be available for all games.
          type: array
          items:
            type: string
        userIDs:
          description: List of player IDs (external). If not provided, free rounds will be available for all players.
          type: array
          items:
            type: string

        currency:
          description: Currency code in ISO4217
          type: string

        quantity:
          description: Number of free rounds.
          type: integer
          format: int32
          minimum: 1
          maximum: 99

        betLine:
          description: Number of bet line configured for this game/provider.
          type: integer
          format: int32
          minimum: 1
          maximum: 99

        validFrom:
          description: Start date when free rounds become available.
          type: string
          format: date-time

        validUntil:
          description: |
            End date when free rounds become unavailable. If not provided then this campaign never ends.
          type: string
          format: date-time

    CreateFreeRoundsResponse:
      type: object
      required:
        - id
        - extID
      properties:
        id:
          description: Free rounds ID (internal).
          type: string
          format: uuid

        extID:
          description: Free rounds ID (external). This is provided in the request.
          type: string

    DeleteFreeRoundsRequest:
      type: object
      required:
        - cID
      properties:
        id:
          description: |
            Free rounds ID (internal). Used as idempotency key. One of id or extID must be provided.
          type: string
          format: uuid

        extID:
          description: |
            Free rounds ID (external). Used as idempotency key. One of id or extID must be provided.
          type: string

        cID:
          description: Client's ID (internal)
          type: string
          format: uuid

    DeleteFreeRoundsRes:
      type: object
      required:
        - id
        - extID
      properties:
        id:
          description: Free rounds ID (internal).
          type: string
          format: uuid

        extID:
          description: Free rounds ID (external). It always provided on create request.
          type: string
