<?php
/**
 * CreateFreeRoundsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SwipeGames\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swipe Games Core Public API
 *
 * This is the Core API for Swipe Games Public API. It provides endpoints to create new games, manage free rounds campaigns, and more.
 *
 * The version of the OpenAPI document: 1.4.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SwipeGames\PublicApi\Core;

use \ArrayAccess;
use \SwipeGames\PublicApi\ObjectSerializer;

/**
 * CreateFreeRoundsRequest Class Doc Comment
 *
 * @category Class
 * @package  SwipeGames\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateFreeRoundsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateFreeRoundsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ext_id' => 'string',
        'c_id' => 'string',
        'ext_cid' => 'string',
        'game_ids' => 'string[]',
        'user_ids' => 'string[]',
        'currency' => 'string',
        'quantity' => 'int',
        'bet_line' => 'int',
        'valid_from' => '\DateTime',
        'valid_until' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ext_id' => null,
        'c_id' => 'uuid',
        'ext_cid' => null,
        'game_ids' => null,
        'user_ids' => null,
        'currency' => null,
        'quantity' => 'int32',
        'bet_line' => 'int32',
        'valid_from' => 'date-time',
        'valid_until' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'ext_id' => false,
        'c_id' => false,
        'ext_cid' => false,
        'game_ids' => false,
        'user_ids' => false,
        'currency' => false,
        'quantity' => false,
        'bet_line' => false,
        'valid_from' => false,
        'valid_until' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ext_id' => 'extID',
        'c_id' => 'cID',
        'ext_cid' => 'extCID',
        'game_ids' => 'gameIDs',
        'user_ids' => 'userIDs',
        'currency' => 'currency',
        'quantity' => 'quantity',
        'bet_line' => 'betLine',
        'valid_from' => 'validFrom',
        'valid_until' => 'validUntil'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ext_id' => 'setExtId',
        'c_id' => 'setCId',
        'ext_cid' => 'setExtCid',
        'game_ids' => 'setGameIds',
        'user_ids' => 'setUserIds',
        'currency' => 'setCurrency',
        'quantity' => 'setQuantity',
        'bet_line' => 'setBetLine',
        'valid_from' => 'setValidFrom',
        'valid_until' => 'setValidUntil'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ext_id' => 'getExtId',
        'c_id' => 'getCId',
        'ext_cid' => 'getExtCid',
        'game_ids' => 'getGameIds',
        'user_ids' => 'getUserIds',
        'currency' => 'getCurrency',
        'quantity' => 'getQuantity',
        'bet_line' => 'getBetLine',
        'valid_from' => 'getValidFrom',
        'valid_until' => 'getValidUntil'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ext_id', $data ?? [], null);
        $this->setIfExists('c_id', $data ?? [], null);
        $this->setIfExists('ext_cid', $data ?? [], null);
        $this->setIfExists('game_ids', $data ?? [], null);
        $this->setIfExists('user_ids', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('bet_line', $data ?? [], null);
        $this->setIfExists('valid_from', $data ?? [], null);
        $this->setIfExists('valid_until', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ext_id'] === null) {
            $invalidProperties[] = "'ext_id' can't be null";
        }
        if ($this->container['c_id'] === null) {
            $invalidProperties[] = "'c_id' can't be null";
        }
        if ($this->container['ext_cid'] === null) {
            $invalidProperties[] = "'ext_cid' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if (($this->container['quantity'] > 99)) {
            $invalidProperties[] = "invalid value for 'quantity', must be smaller than or equal to 99.";
        }

        if (($this->container['quantity'] < 1)) {
            $invalidProperties[] = "invalid value for 'quantity', must be bigger than or equal to 1.";
        }

        if ($this->container['bet_line'] === null) {
            $invalidProperties[] = "'bet_line' can't be null";
        }
        if (($this->container['bet_line'] > 99)) {
            $invalidProperties[] = "invalid value for 'bet_line', must be smaller than or equal to 99.";
        }

        if (($this->container['bet_line'] < 1)) {
            $invalidProperties[] = "invalid value for 'bet_line', must be bigger than or equal to 1.";
        }

        if ($this->container['valid_from'] === null) {
            $invalidProperties[] = "'valid_from' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ext_id
     *
     * @return string
     */
    public function getExtId()
    {
        return $this->container['ext_id'];
    }

    /**
     * Sets ext_id
     *
     * @param string $ext_id Free rounds ID (external). Used as idempotency key. Same ID can be used to create free rounds only once.
     *
     * @return self
     */
    public function setExtId($ext_id)
    {
        if (is_null($ext_id)) {
            throw new \InvalidArgumentException('non-nullable ext_id cannot be null');
        }
        $this->container['ext_id'] = $ext_id;

        return $this;
    }

    /**
     * Gets c_id
     *
     * @return string
     */
    public function getCId()
    {
        return $this->container['c_id'];
    }

    /**
     * Sets c_id
     *
     * @param string $c_id Client's ID (internal)
     *
     * @return self
     */
    public function setCId($c_id)
    {
        if (is_null($c_id)) {
            throw new \InvalidArgumentException('non-nullable c_id cannot be null');
        }
        $this->container['c_id'] = $c_id;

        return $this;
    }

    /**
     * Gets ext_cid
     *
     * @return string
     */
    public function getExtCid()
    {
        return $this->container['ext_cid'];
    }

    /**
     * Sets ext_cid
     *
     * @param string $ext_cid External Client's ID (game aggregator or casino)
     *
     * @return self
     */
    public function setExtCid($ext_cid)
    {
        if (is_null($ext_cid)) {
            throw new \InvalidArgumentException('non-nullable ext_cid cannot be null');
        }
        $this->container['ext_cid'] = $ext_cid;

        return $this;
    }

    /**
     * Gets game_ids
     *
     * @return string[]|null
     */
    public function getGameIds()
    {
        return $this->container['game_ids'];
    }

    /**
     * Sets game_ids
     *
     * @param string[]|null $game_ids List of game IDs. If not provided, free rounds will be available for all games.
     *
     * @return self
     */
    public function setGameIds($game_ids)
    {
        if (is_null($game_ids)) {
            throw new \InvalidArgumentException('non-nullable game_ids cannot be null');
        }
        $this->container['game_ids'] = $game_ids;

        return $this;
    }

    /**
     * Gets user_ids
     *
     * @return string[]|null
     */
    public function getUserIds()
    {
        return $this->container['user_ids'];
    }

    /**
     * Sets user_ids
     *
     * @param string[]|null $user_ids List of player IDs (external). If not provided, free rounds will be available for all players.
     *
     * @return self
     */
    public function setUserIds($user_ids)
    {
        if (is_null($user_ids)) {
            throw new \InvalidArgumentException('non-nullable user_ids cannot be null');
        }
        $this->container['user_ids'] = $user_ids;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency Currency code in ISO4217
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity Number of free rounds.
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }

        if (($quantity > 99)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling CreateFreeRoundsRequest., must be smaller than or equal to 99.');
        }
        if (($quantity < 1)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling CreateFreeRoundsRequest., must be bigger than or equal to 1.');
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets bet_line
     *
     * @return int
     */
    public function getBetLine()
    {
        return $this->container['bet_line'];
    }

    /**
     * Sets bet_line
     *
     * @param int $bet_line Number of bet line configured for this game/provider. You can find more information in related section [Free Rounds Bet Lines](/public-api/free-rounds-bet-lines).
     *
     * @return self
     */
    public function setBetLine($bet_line)
    {
        if (is_null($bet_line)) {
            throw new \InvalidArgumentException('non-nullable bet_line cannot be null');
        }

        if (($bet_line > 99)) {
            throw new \InvalidArgumentException('invalid value for $bet_line when calling CreateFreeRoundsRequest., must be smaller than or equal to 99.');
        }
        if (($bet_line < 1)) {
            throw new \InvalidArgumentException('invalid value for $bet_line when calling CreateFreeRoundsRequest., must be bigger than or equal to 1.');
        }

        $this->container['bet_line'] = $bet_line;

        return $this;
    }

    /**
     * Gets valid_from
     *
     * @return \DateTime
     */
    public function getValidFrom()
    {
        return $this->container['valid_from'];
    }

    /**
     * Sets valid_from
     *
     * @param \DateTime $valid_from Start date when free rounds become available.
     *
     * @return self
     */
    public function setValidFrom($valid_from)
    {
        if (is_null($valid_from)) {
            throw new \InvalidArgumentException('non-nullable valid_from cannot be null');
        }
        $this->container['valid_from'] = $valid_from;

        return $this;
    }

    /**
     * Gets valid_until
     *
     * @return \DateTime|null
     */
    public function getValidUntil()
    {
        return $this->container['valid_until'];
    }

    /**
     * Sets valid_until
     *
     * @param \DateTime|null $valid_until End date when free rounds become unavailable. If not provided then this campaign never ends. If you provide finite validity duration, it should not exceed 30 days.
     *
     * @return self
     */
    public function setValidUntil($valid_until)
    {
        if (is_null($valid_until)) {
            throw new \InvalidArgumentException('non-nullable valid_until cannot be null');
        }
        $this->container['valid_until'] = $valid_until;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


