<?php
/**
 * GameInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SwipeGames\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Swipe Games Core Public API
 *
 * This is the Core API for Swipe Games Public API. It provides endpoints to create new games, manage free rounds campaigns, and more.
 *
 * The version of the OpenAPI document: 1.2.20
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SwipeGames\PublicApi\Core;

use \ArrayAccess;
use \SwipeGames\PublicApi\ObjectSerializer;

/**
 * GameInfo Class Doc Comment
 *
 * @category Class
 * @package  SwipeGames\PublicApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GameInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GameInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'title' => 'string',
        'id' => 'string',
        'locales' => 'string[]',
        'currencies' => 'string[]',
        'platforms' => '\SwipeGames\PublicApi\Core\PlatformType[]',
        'images' => '\SwipeGames\PublicApi\Core\GameInfoImages',
        'has_free_spins' => 'bool',
        'rtp' => 'int',
        'bet_lines' => '\SwipeGames\PublicApi\Core\BetLineInfo[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'title' => null,
        'id' => null,
        'locales' => null,
        'currencies' => null,
        'platforms' => null,
        'images' => null,
        'has_free_spins' => null,
        'rtp' => null,
        'bet_lines' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'title' => false,
        'id' => false,
        'locales' => false,
        'currencies' => false,
        'platforms' => false,
        'images' => false,
        'has_free_spins' => false,
        'rtp' => false,
        'bet_lines' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'title' => 'title',
        'id' => 'id',
        'locales' => 'locales',
        'currencies' => 'currencies',
        'platforms' => 'platforms',
        'images' => 'images',
        'has_free_spins' => 'hasFreeSpins',
        'rtp' => 'rtp',
        'bet_lines' => 'betLines'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'title' => 'setTitle',
        'id' => 'setId',
        'locales' => 'setLocales',
        'currencies' => 'setCurrencies',
        'platforms' => 'setPlatforms',
        'images' => 'setImages',
        'has_free_spins' => 'setHasFreeSpins',
        'rtp' => 'setRtp',
        'bet_lines' => 'setBetLines'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'title' => 'getTitle',
        'id' => 'getId',
        'locales' => 'getLocales',
        'currencies' => 'getCurrencies',
        'platforms' => 'getPlatforms',
        'images' => 'getImages',
        'has_free_spins' => 'getHasFreeSpins',
        'rtp' => 'getRtp',
        'bet_lines' => 'getBetLines'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('locales', $data ?? [], null);
        $this->setIfExists('currencies', $data ?? [], null);
        $this->setIfExists('platforms', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('has_free_spins', $data ?? [], null);
        $this->setIfExists('rtp', $data ?? [], null);
        $this->setIfExists('bet_lines', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['locales'] === null) {
            $invalidProperties[] = "'locales' can't be null";
        }
        if ($this->container['currencies'] === null) {
            $invalidProperties[] = "'currencies' can't be null";
        }
        if ($this->container['platforms'] === null) {
            $invalidProperties[] = "'platforms' can't be null";
        }
        if ($this->container['images'] === null) {
            $invalidProperties[] = "'images' can't be null";
        }
        if ($this->container['has_free_spins'] === null) {
            $invalidProperties[] = "'has_free_spins' can't be null";
        }
        if ($this->container['rtp'] === null) {
            $invalidProperties[] = "'rtp' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title Game's title in English
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Game's ID (internal)
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets locales
     *
     * @return string[]
     */
    public function getLocales()
    {
        return $this->container['locales'];
    }

    /**
     * Sets locales
     *
     * @param string[] $locales List of supported locales in IETF BCP 47 format (ISO 639-1 language code with optional ISO 3166-1 country code), using underscore as separator.
     *
     * @return self
     */
    public function setLocales($locales)
    {
        if (is_null($locales)) {
            throw new \InvalidArgumentException('non-nullable locales cannot be null');
        }
        $this->container['locales'] = $locales;

        return $this;
    }

    /**
     * Gets currencies
     *
     * @return string[]
     */
    public function getCurrencies()
    {
        return $this->container['currencies'];
    }

    /**
     * Sets currencies
     *
     * @param string[] $currencies List of supported currency codes in ISO 4217 format
     *
     * @return self
     */
    public function setCurrencies($currencies)
    {
        if (is_null($currencies)) {
            throw new \InvalidArgumentException('non-nullable currencies cannot be null');
        }
        $this->container['currencies'] = $currencies;

        return $this;
    }

    /**
     * Gets platforms
     *
     * @return \SwipeGames\PublicApi\Core\PlatformType[]
     */
    public function getPlatforms()
    {
        return $this->container['platforms'];
    }

    /**
     * Sets platforms
     *
     * @param \SwipeGames\PublicApi\Core\PlatformType[] $platforms List of supported platform types
     *
     * @return self
     */
    public function setPlatforms($platforms)
    {
        if (is_null($platforms)) {
            throw new \InvalidArgumentException('non-nullable platforms cannot be null');
        }
        $this->container['platforms'] = $platforms;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \SwipeGames\PublicApi\Core\GameInfoImages
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \SwipeGames\PublicApi\Core\GameInfoImages $images images
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets has_free_spins
     *
     * @return bool
     */
    public function getHasFreeSpins()
    {
        return $this->container['has_free_spins'];
    }

    /**
     * Sets has_free_spins
     *
     * @param bool $has_free_spins If game supports free spins
     *
     * @return self
     */
    public function setHasFreeSpins($has_free_spins)
    {
        if (is_null($has_free_spins)) {
            throw new \InvalidArgumentException('non-nullable has_free_spins cannot be null');
        }
        $this->container['has_free_spins'] = $has_free_spins;

        return $this;
    }

    /**
     * Gets rtp
     *
     * @return int
     */
    public function getRtp()
    {
        return $this->container['rtp'];
    }

    /**
     * Sets rtp
     *
     * @param int $rtp Game's RTP
     *
     * @return self
     */
    public function setRtp($rtp)
    {
        if (is_null($rtp)) {
            throw new \InvalidArgumentException('non-nullable rtp cannot be null');
        }
        $this->container['rtp'] = $rtp;

        return $this;
    }

    /**
     * Gets bet_lines
     *
     * @return \SwipeGames\PublicApi\Core\BetLineInfo[]|null
     */
    public function getBetLines()
    {
        return $this->container['bet_lines'];
    }

    /**
     * Sets bet_lines
     *
     * @param \SwipeGames\PublicApi\Core\BetLineInfo[]|null $bet_lines List of bet lines supported for this game per currency. Available only if game has free spins. See more info in related section [Free Rounds Bet Lines](/public-api/free-rounds-bet-lines).
     *
     * @return self
     */
    public function setBetLines($bet_lines)
    {
        if (is_null($bet_lines)) {
            throw new \InvalidArgumentException('non-nullable bet_lines cannot be null');
        }
        $this->container['bet_lines'] = $bet_lines;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


