// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ErrorResponseCode.
const (
	AccountBlocked        ErrorResponseCode = "account_blocked"
	BetLimit              ErrorResponseCode = "bet_limit"
	ClientConnectionError ErrorResponseCode = "client_connection_error"
	CurrencyNotSupported  ErrorResponseCode = "currency_not_supported"
	GameNotFound          ErrorResponseCode = "game_not_found"
	InsufficientFunds     ErrorResponseCode = "insufficient_funds"
	LocaleNotSupported    ErrorResponseCode = "locale_not_supported"
	LossLimit             ErrorResponseCode = "loss_limit"
	SessionExpired        ErrorResponseCode = "session_expired"
	SessionNotFound       ErrorResponseCode = "session_not_found"
	TimeLimit             ErrorResponseCode = "time_limit"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case AccountBlocked:
		return true
	case BetLimit:
		return true
	case ClientConnectionError:
		return true
	case CurrencyNotSupported:
		return true
	case GameNotFound:
		return true
	case InsufficientFunds:
		return true
	case LocaleNotSupported:
		return true
	case LossLimit:
		return true
	case SessionExpired:
		return true
	case SessionNotFound:
		return true
	case TimeLimit:
		return true
	default:
		return false
	}
}

// ErrorResponse General error response for Swipe Games Public API. Usually used for Public API responses.
type ErrorResponse struct {
	// Code Error code.
	Code *ErrorResponseCode `json:"code,omitempty"`

	// Details Technical details for the error. Could be used for debugging, should not be shown to the player.
	Details *string `json:"details,omitempty"`

	// Message A brief description of the error in English. Could be shown to the player.
	Message string `json:"message"`
}

// ErrorResponseCode Error code.
type ErrorResponseCode string

// User defines model for User.
type User struct {
	// Country Country code ISO 3166-1 alpha-2.
	Country   *string `json:"country,omitempty"`
	FirstName *string `json:"firstName,omitempty"`

	// Id User's ID (external). This is User's ID on your side.
	Id       string  `json:"id"`
	LastName *string `json:"lastName,omitempty"`
	NickName *string `json:"nickName,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4yUwU8bOxDG/5WRL+89aVm9gMQhN0QR4tKiAidaRY53NjvFO+N67EKE8r9XdiChbFr1",
	"lHi+b+yfP9v7bJyMQRg5qZk/G3UDjrb+vYhR4mfUIKxYCh2qixQSCZu5uUTGaD1gsUF88UEvEW4eKSBc",
	"2hEVrvPSk4Oz66sW7jRb79eQFbtq3Iu7CbT9wqYxIUrAmAgripPuAEEFhKK1pjHIeTTze7OyIy5Y0qKX",
	"zJ1pjMsxIrt1LWoOQWLCInhx1uOkbJ2TzGmx9OIeamWJaeFppFSbVHeDRCPuBsSa+54cIadFn7lT0xhF",
	"VRJe4FOgWCd7rfyC6GuTE2Z0qfrL3szXxqR1QDM3miLxymwa02Gy5HUaxy26gclZDy+WGnEacHtELZxL",
	"9h0scZ9/h8u8WhGvGtChqiypOHSQR4YktT14u8ZYMp7AjKhqVwfO5gyWkbCHN1WQfk8DxHDBK086vAH7",
	"u2U3jYn4Pdc85/c7hn1YsvyGLhW+O8VY4N5fp8wprqfU51uh3im4uvkEJ7PT06MZWB8Ge3R8MIKeoqaP",
	"dqwhTFTqpqsUqH8Urj7Av/iUMLL1/7VwO5ACKexVYVhLjqC0veGTyb39w8pM7uE34rsAqTuQXTER91Lb",
	"KfmivX3X5zKOwuXn9evRmB8YdbvFWXvczk4LhgRkG8jMzUn7f3tSnrZNQzmGzeZnAAAA//85QgKCfQQA",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
