// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ErrorResponseCode.
const (
	AccountBlocked        ErrorResponseCode = "account_blocked"
	BetLimit              ErrorResponseCode = "bet_limit"
	ClientConnectionError ErrorResponseCode = "client_connection_error"
	CurrencyNotSupported  ErrorResponseCode = "currency_not_supported"
	GameNotFound          ErrorResponseCode = "game_not_found"
	InsufficientFunds     ErrorResponseCode = "insufficient_funds"
	LocaleNotSupported    ErrorResponseCode = "locale_not_supported"
	LossLimit             ErrorResponseCode = "loss_limit"
	SessionExpired        ErrorResponseCode = "session_expired"
	SessionNotFound       ErrorResponseCode = "session_not_found"
	TimeLimit             ErrorResponseCode = "time_limit"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case AccountBlocked:
		return true
	case BetLimit:
		return true
	case ClientConnectionError:
		return true
	case CurrencyNotSupported:
		return true
	case GameNotFound:
		return true
	case InsufficientFunds:
		return true
	case LocaleNotSupported:
		return true
	case LossLimit:
		return true
	case SessionExpired:
		return true
	case SessionNotFound:
		return true
	case TimeLimit:
		return true
	default:
		return false
	}
}

// ErrorResponse General error response for Swipe Games Public API. Usually used for Public API responses.
type ErrorResponse struct {
	// Code Error code.
	Code *ErrorResponseCode `json:"code,omitempty"`

	// Details Technical details for the error. Could be used for debugging, should not be shown to the player.
	Details *string `json:"details,omitempty"`

	// Message A brief description of the error in English. Could be shown to the player.
	Message string `json:"message"`
}

// ErrorResponseCode Error code.
type ErrorResponseCode string

// User defines model for User.
type User struct {
	// Country Country code ISO 3166-1 alpha-2.
	Country   *string `json:"country,omitempty"`
	FirstName *string `json:"firstName,omitempty"`

	// Id User's ID (external). This is User's ID on your side.
	Id       string  `json:"id"`
	LastName *string `json:"lastName,omitempty"`
	NickName *string `json:"nickName,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4yU0U8bORDG/5WRX+5OWlYXkDgpb4hDiJcWFXiiVeR4Z7NTvDOuxy5EKP97ZQcSyqZV",
	"nxLP943982d7n42TMQgjJzXzZ6NuwNHWvxcxSvyEGoQVS6FDdZFCImEzN5fIGK0HLDaILz7oJcLNIwWE",
	"SzuiwnVeenJwdn3Vwp1m6/0asmJXjXtxN4G2n9k0JkQJGBNhRXHSHSCogFC01jQGOY9mfm9WdsQFS1r0",
	"krkzjXE5RmS3rkXNIUhMWAQvznqclK1zkjktll7cQ60sMS08jZRqk+pukGjE3YBYc9+TI+S06DN3ahqj",
	"qErCC3wKFOtkr5WfEH1tcsKMLlV/2Zv50pi0DmjmRlMkXplNYzpMlrxO47hFNzA56+HFUiNOA26PqIVz",
	"yb6DJe7z73CZVyviVQM6VJUlFYcO8siQpLYHb9cYS8YTmBFV7erA2ZzBMhL28KYK0u9pgBgueOVJhzdg",
	"f7bspjERv+Wa5/x+x7APS5Zf0aXCd6cYC9z765Q5xfWU+nwr1DsFVzcf4WR2eno0A+vDYI+OD0bQU9T0",
	"wY41hIlK3XSVAvWXwtX/8Dc+JYxs/T8t3A6kQAp7VRjWkiMobW/4ZHJvf7Myk3v4hfguQOoOZFdMxL3U",
	"dkq+aG/f9bmMo3D5ef16NOY7Rt1ucdYet7P/CoYEZBvIzM1J+297Up62TUM5hs3mRwAAAP//ytLwtH0E",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
